### ISSUE TITLE
[Question]: How do I make lightline statusline larger

### ISSUE THREAD

**Issue by danielmkarlsson** [davidgranstrom/scnvim#100]
My statusline lloks like this right now:
`1,1 |< % 3.37% 1048u 24s [sclang]`

In the 
`" create a custom status line for supercollider buffers`
section of README.md, this line:
`setlocal stl+=%24.24{scnvim#statusline#server_status()}`
shows me how to make more room for the statusline so that it can show all of it's information.

I am new to lightline because I am new to Linux.
What is the corresponding configuration line in lightline?
It might could be a good idea to include it in this section:

```
" lightline.vim example
" let g:lightline = {}
" let g:lightline.component_function = {
"   \ 'server_status': 'scnvim#statusline#server_status',
"   \ }
"
" function! s:set_sclang_lightline_stl()
"   let g:lightline.active = {
"   \ 'left':  [ [ 'mode', 'paste' ],
"   \          [ 'readonly', 'filename', 'modified' ] ],
"   \ 'right': [ [ 'lineinfo' ],
"   \            [ 'percent' ],
"   \            [ 'server_status'] ]
"   \ }
" endfunction
```

What do you say?

**Comment by davidgranstrom** [comment]
Hi! I'm no longer a lightline.vim user myself, but maybe there is a way to configure the (lightline) component somehow to increase its default size. I would take a look into the lightline.vim docs.

The return value of `scnvim#statusline#server_status()` function is simply a formatted string with the server info, so styling is left to the consumer of the API. I would be happy to accept a PR with an updated instruction on how to specify this for lightline.
