### ISSUE TITLE
[FR]: Autocompletion for arguments

### ISSUE THREAD

**Issue by grammoboy2** [davidgranstrom/scnvim#101]
In SCIDE you can autocomplete arguments. So for SinOsc.ar( if you hit <TAB> now, it fills in: freq: for you. 
You fill in the number: freq: 440, . And when you put a comma after it, it autocompletes for you the other argument via <TAB> and so on.

Scnvim, shows me which arguments should go there, but doesn't autocomplete AFAIK.

(Btw: scnvim is great, thx!)

**Comment by davidgranstrom** [comment]
> In SCIDE you can autocomplete arguments. So for SinOsc.ar( if you hit now, it fills in: freq: for you.
> You fill in the number: freq: 440, . And when you put a comma after it, it autocompletes for you the other argument via and so on.
> 
> Scnvim, shows me which arguments should go there, but doesn't autocomplete AFAIK.

Do you mean something like this?

![signature](https://user-images.githubusercontent.com/672917/55289973-95e93300-53cd-11e9-8833-e51c6e4d5afc.png)

That is something I've been working on, but unfortunately its not ready yet. I will get back to it when 1.0.0 is released. But you can follow the progress from [this branch](https://github.com/davidgranstrom/scnvim/tree/topic/arghints-lua) if you're curious.

> 
> (Btw: scnvim is great, thx!)

Thank you!

**Comment by grammoboy2** [comment]
For the screenshot, indeed If you hit <TAB> now and it would fill in 'freq', that's the behavior you get with the SCIDE, but I guess you know.

The Snippet generator in the last video on scnvim github readme.md, looks similar too, I saw later.
