### ISSUE TITLE
[BUG] Class library recompile

### ISSUE THREAD

**Issue by davidgranstrom** [davidgranstrom/scnvim#104]
**Describe the bug**

Class library cannot be recompiled (again) if there are syntax errors in class files.

**Expected behavior**

Be able to recompile even if there are errors.

**Steps to reproduce**

Create a class file in a SuperCollider compilation path, make a syntax error and recompile class library.

Result:
```
Library has not been compiled successfully.
```

**Additional context**

The work around is to restart scnvim. This is a regression since this was working before the recompile routine was rewritten.

**Comment by john-d-murphy** [comment]
I find that I can't do an "SCNvimStop" when this bug happens, either. 
From what I can tell, this is a language issue, where the function "recompile" isn't defined because the language hasn't compiled.
Seems like there has to be a workaround because restarting the entire process because of a missing semicolon in a class  you're hacking on seems excessive.

**Comment by davidgranstrom** [comment]
@john-d-murphy Good catch, I'll see if I can find a solution for `SCNvimClose` if the class library couldn't be compiled. I'm guessing that we'll need to call `jobstop()` in such a scenario, but this is not something that should be called under normal conditions since some shutdown actions in sclang won't be triggered as opposed to `0.exit`.

I'll open a new issue for `SCNvimClose` since this particular issue will hopefully be resolved by #106.

**Comment by laelume** [comment]
Hi, this is the most recent / relevant thing I could find related to command line usage of Recompile Class Library (headless / GUI-less) so I'm sorry if this is not the best place to post this following question: 
could you please specify what command line instructions you're using to recompile the class library? I have found very little documentation on the uses of .recompile and SCCLassLibrary and am running sclang from an command line ssh into linux (raspi) . Thanks!

**Comment by davidgranstrom** [comment]
@laelume Hi! If you are using the readline interface for sclang I think you can use `C-x` (enter) to recompile the class lib.
