### ISSUE TITLE
[Question]: SCNVim + JitLibExtensions 

### ISSUE THREAD

**Issue by gilfuser** [davidgranstrom/scnvim#109]
Hi there!
This is something that have been happening since there was a change in the design of some of the JitLib family Quarks: JitLibExtensions, adclib and Influx (and maybe some other more).
In order to improve the compatibility with headless use of SuperCollider, all the GUI things went to a folder called scide_scqt/GUI
I couldn't figure out by my own how this works exactly, but it seems that a.t.m. those GUIs only work with scide. If one tries to use, e.g. ProxyChainGui in scnvim, the class won't be found.
I tried to find a way to solve this but it's probably something out from my league. I searched at both sides for something that could contain a clue without success.

Is there someone out there that could point me a way of making possible to use JitLib GUI with scnvim?

Any help will be much appreciated

All the best,
Gil

**Comment by davidgranstrom** [comment]
Hi,

Yes, the `scide_*` directories are only sourced if the name matches the frontend as you noted. This is specified by the `-i` command line option for `sclang` and scnvim will (and must) use `-i scnvim` to avoid collisions with the `Document` class which is implemented differently for each frontend i.e. ScIDE. Maybe there are references in those classes which depends on features of ScIDE (or maybe ScIDEs implementation of Document)?

Perhaps you could modify `sclang_conf.yaml` to include the absolute path to `scide_scqt/GUI`, that would be the easiest solution that I can think of at the moment. You will find `sclang_conf.yaml` in your Extensions directory (there is also shortcut in one of the menus in the IDE if I remember correctly).

**Comment by gilfuser** [comment]
Yes! That did it! Thank you!
I thought that explicit including the absolute path to `scide_scqt/GUI` would call it twice in scide, but actually it didn't. So there are no counter effects.

all the best,
Gil
