### ISSUE TITLE
[BUG] Scnvim freezes when trying to recompile or close while SerialDevice is active

### ISSUE THREAD

**Issue by kflak** [davidgranstrom/scnvim#114]
**Describe the bug**

I'm currently working with DMX, specifically an EntTec USBPro interface and the DMX quark.

**Expected behavior**

When closing nvim, I would like it to close all serial connections.

**Steps to reproduce**

Trigger a long-running light fade:
```
~dmx.blackout(60);
```
and try to close. The post buffer will be filled with 
```
WARNING: SerialPort not open
```
until the fade is over.

**Additional context**

**Information**
- `nvim --version`: NVIM v0.4.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.4/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

- Operating system: Arch Linux, 5.6.19-rt12-1-rt

- Running scnvim in a Terminal/GUI: alacritty

**Comment by davidgranstrom** [comment]
Thanks for the report. Does this happen in ScIDE as well? Or `sclang file.scd` on the command line? If not, there is something missing in the shutdown sequence in scnvim that we need to investigate.

**Comment by kflak** [comment]
Hi,

It seems to be an sclang thing, I'm getting the exact same behavior in both scide and scnvim. Would it be an idea to close this here, and rather open an issue in sc instead?

**Comment by davidgranstrom** [comment]
@kflak Ok, thanks for confirming. Yes, that might be a good idea. I guess it would be good to rule out if this is something specific to the quark you mention or something more general with the `SerialPort` class before logging an issue.

A scnvim specific workaround might be to register an autocommand on `VimLeavePre` to close all SerialPorts before exiting, something like:

```viml
au! VimLeavePre *.scd,*.sc call scnvim#sclang#send_silent('SerialPort.closeAll;')
```
