### ISSUE TITLE
[BUG] error in manual installation wiki page

### ISSUE THREAD

**Issue by madskjeldgaard** [davidgranstrom/scnvim#116]
There is a small error in the symbolic link in the linux instructions on the manual installation page:

```
ln -s /home/<USER>/.config/nvim/plugged/scnvim/sc /home/<USER>/.local/share/SuperCollider/Extensions/scide_scnvim/scnvim
```
should be 
```
ln -s /home/<USER>/.config/nvim/plugged/scnvim/scide_scnvim /home/<USER>/.local/share/SuperCollider/Extensions/scide_scnvim/scnvim
```

**Comment by salkin-mada** [comment]
i guess it's just one example of a link. when done manually it could change?
on this machine where its installed via vimplug it's off course is at ~/.local/share/SuperCollider/Extensions containing this link-> `scide_scnvim -> /home/salkin/.vim/plugged/scnvim/scide_scnvim`

**Comment by madskjeldgaard** [comment]
but the problem is it is linking from `sc` in the plugin folder in the example, and not `scide_scnvim`. The first doesn't exist, at least not on mine :)

**Comment by davidgranstrom** [comment]
@madskjeldgaard Thanks for the report! I've updated the installation instructions.

https://github.com/davidgranstrom/scnvim/wiki/Manual-installation-of-SuperCollider-classes
