### ISSUE TITLE
[Question]: lightline compatibility

### ISSUE THREAD

**Issue by ranjithshegde** [davidgranstrom/scnvim#118]
I am trying to get the statusline working alongside ligthline

I have the following in my rc file

```
function! s:startSCNvim()

let g:lightline = {}
    let g:lightline.component_function = {
                \ 'server_status': 'scnvim#statusline#server_status',
                \ 'gitbranch': 'FugitiveHead'
                \ }

    function! s:set_sclang_lightline_stl()
        let g:lightline.active = {
                    \ 'left':  [ [ 'mode', 'paste' ],
                    \          [ 'gitbranch', 'readonly', 'filename', 'modified' ] ],
                    \ 'right': [ [ 'lineinfo' ],
                    \            [ 'percent' ],
                    \            [ 'server_status'] ]
                    \ }
    endfunction 
    call s:set_sclang_lightline_stl()

endfunction 

augroup sclang
	autocmd!
	autocmd FileType supercollider call s:startSCNvim()
augroup end
```
when I launch nvim with a specific sc file (nvim foo.scd) and start scnvim+boot server and call the scnvimstatusline it does pop up. However, if I open scnvim first and then open a sc file (e: foo.scd) and repeat the above process, the statusline does not show/

can someone please tell me what I am doing wrong or omitting?
	

Distro: Arch
SCNvim version: latest github version
nvim : 0.4.4
supercollider version: 3.11.1

**Comment by davidgranstrom** [comment]
@ranjithshegde It was a while since I used lightline myself, but you could give this a try:

```vim
" lightline.vim example

let g:lightline = {}
let g:lightline.component_function = {
  \ 'server_status': 'scnvim#statusline#server_status',
  \ }

function! s:set_sclang_lightline_stl()
  let g:lightline.active = {
  \ 'left':  [ [ 'mode', 'paste' ],
  \          [ 'readonly', 'filename', 'modified' ] ],
  \ 'right': [ [ 'lineinfo' ],
  \            [ 'percent' ],
  \            [ 'server_status'] ]
  \ }
endfunction

augroup scnvim_stl
  autocmd!
  autocmd FileType supercollider call <SID>set_sclang_statusline()
augroup END
```

**Comment by ranjithshegde** [comment]
thanks for your response

I get the following error when I open a sc file with your suggestion

`
Error detected while processing FileType Autocommands for "supercollider":
E117: Unknowm function <SNR>3_set_sclang_statusline
`

**Comment by davidgranstrom** [comment]
Sorry, there was a copy/paste error earlier referencing the wrong function. Should work better now.

**Comment by ranjithshegde** [comment]
ah right, I missed it too..

But its the same issue. statusline works only if I lauch nvim with an scd file. not file I launch nvim first and open an sc file from within

**Comment by davidgranstrom** [comment]
Hmm, maybe something has changed in lightline since I wrote that. You could try and put a `echom "scnvim"` statement inside `s:set_sclang_lightline_stl()` just to see that it actually fires. So, first start nvim without any file, and then `:e foo.scd` and you should see "scnvim" echoed to the cmd line (you might need to check with `:messages` in case it gets overwritten by something else)

**Comment by ranjithshegde** [comment]
That works. I see scnvim echoed (twice)

Also, Here is the difference I see. 
When I open nvim without a file and open an sc file (e: ) then I have the usual lightline elements

If I open nvim with a sc file then on the right side I only have the cursor position and percentage of the document without the utf-8 etc.. so that when i launch scnvim and call status, it has space to be displayed

**Comment by davidgranstrom** [comment]
Okay, I just tested with lightline.vim and it didn't work here either, so it seems that something has changed since I last used it. I'm not sure what the proper solution on updating the components conditionally based on FileType, but a solution that does work is to simply have a configuration that could be used for all file types, including SuperCollider, like this:

```vim
let g:lightline = {}
let g:lightline.component_function = {
      \ 'server_status': 'scnvim#statusline#server_status',
      \ }

let g:lightline.active = {
      \ 'left':  [ [ 'mode', 'paste' ],
      \          [ 'readonly', 'filename', 'modified' ] ],
      \ 'right': [ [ 'lineinfo' ],
      \            [ 'percent' ],
      \            [ 'server_status'] ]
      \ }
```

I will update the example configuration with the example above.
