### ISSUE TITLE
Incomplete lines in post window output

### ISSUE THREAD

**Issue by danielmkarlsson** [davidgranstrom/scnvim#119]
`.trace` and similar give inconsistent results where at times only one parameter is seen, sometimes with, sometimes without it's value and sometimes just as the first character of that message.

I thought that `.trace` and similar diagnostic tools would be able to show it's data reliably in the post window.

Run this code in scnvim to reproduce the error:
```
(
Pbind(
    \freq, Pwhite(100,500), 
    \dur, Prand([0.15, 0.25, 0.3], inf),
    \amp, 0.2,
    \legato, 0.3,
).trace.play;
)
```

Here is some sample output from my post window from when I ran the above code:
```
( 'legato': 0.3, 'dur': 0.15, 'amp': 0.2, 'freq': 271 )
( 'legato': 0.3
( 'legato': 0.3, 'dur': 0.3, 'amp': 0.2, 'freq': 340 )
( 'legato': 
( 'legato': 0.3, 'dur': 0.15, 'amp': 0.2, 'freq': 247 )
( 'legato': 0.3
( 'legato': 0.3, 'dur': 0.3, 'amp': 0.2, 'freq': 374 )
( 'legato': 0.3
( 'legato': 0.3, 'dur': 0.25, 'amp': 0.2, 'freq': 215 )
( 'legato': 
( 'legato': 0.3, 'dur': 0.15, 'amp': 0.2, 'freq': 169 )
( 'legato': 0.3
( 'legato': 0.3, 'dur': 0.3, 'amp': 0.2, 'freq': 163 )
( 'legato': 0.3
( 'legato': 0.3, 'dur': 0.3, 'amp': 0.2, 'freq': 382 )
( 
( 'legato': 0.3, 'dur': 0.3, 'amp': 0.2, 'freq': 166 )
( 'legato': 0.3
( 'legato': 0.3, 'dur': 0.25, 'amp': 0.2, 'freq': 294 )
( 'legato': 0.3
( 'legato': 0.3, 'dur': 0.25, 'amp': 0.2, 'freq': 177 )
( 'legato': 0.3
```

NVIM v0.4.3
Mac OS X 10.12.6
Running scnvim in Kitty

**Comment by davidgranstrom** [comment]
Thanks for the report! I've noticed this as well (especially with `.trace`). I think this is a buffering issue, and I haven't found away around it yet (in viml). My plan is to move this part of the code to lua and at the same time fix some issues, this one included. I'll keep this open until there is a PR.
