### ISSUE TITLE
[BUG] Non-indented code isn't treated as a block

### ISSUE THREAD

**Issue by madskjeldgaard** [davidgranstrom/scnvim#12]
There is still some problems with identifying blocks of code if the contents aren't indented properly. 

Here is a simple example:
```
// This doesn't work
(
Pdef(\hello,
	Pbind(\dur, 0.5)
);

Pdef(\helloagain,
	Pbind()
);
)

// This works
(
	Pdef(\hello,
		Pbind(\dur, 0.5)
	);

	Pdef(\helloagain,
		Pbind()
	);
)
```

**Information**
- `nvim --version`: 0.3.4
- Operating system: MacOS 10.14.3
- Running scnvim in a Terminal/GUI: Terminal (iterm2)

**Comment by davidgranstrom** [comment]
Thanks for the report!
Looks like #11 resolves this, I'll merge it later tonight after I've done some more testing.

**Comment by madskjeldgaard** [comment]
uuuh, okay!
