### ISSUE TITLE
[FR]: TOC/Links in help files

### ISSUE THREAD

**Issue by madskjeldgaard** [davidgranstrom/scnvim#127]
**Is your feature request related to a problem? Please describe.**
It can be hard to navigate large help files in the vim help browser as the help files are now. They lack some of the features we see in most vim help files like a Table of Contents to help navigate and get an overview of the content.

**Describe the solution you'd like**

It would be awesome if we had a table of contents at the top of SC help files in SCNvim ala the way the native documentation is structured. Maybe this is part of a bigger idea for tagging the help files with links included but a TOC would get us a long way. 

I am dreaming of something along the lines of this:
![2020-11-06-110547_1920x1080_scrot](https://user-images.githubusercontent.com/22474608/98353779-15b29700-2020-11eb-8cb3-556a6d355659.png)

Where the blue links would be section headers in the SuperCollider help file.

**Describe alternatives you've considered**
I haven't considered alternatives

**Additional context**
No additionel context, I guess.

**Comment by davidgranstrom** [comment]
Have you tried `gO` in a supercollider help buffer? I think this is pretty close to what you describe. Maybe it would be possible to dynamically create TOC and present it in a floating window as well, that would be pretty cool.

Example:

![Screenshot 2020-11-06 at 12 21 38](https://user-images.githubusercontent.com/672917/98360759-b312c880-202a-11eb-8b5d-9ebb9ad6bbe4.png)

**Comment by madskjeldgaard** [comment]
Haha, no I actually hadn't. That's really cool!

**Comment by davidgranstrom** [comment]
:) It is actually an nvim feature (not specific to scnvim), its super useful for browsing nvim docs and man pages as well!
