### ISSUE TITLE
[BUG] scnvim#install breaks with latest update

### ISSUE THREAD

**Issue by kflak** [davidgranstrom/scnvim#128]
**Describe the bug**

Getting this when calling `scnvim#install()`: 
```
Error detected while processing function scnvim#install:
line    1:
E5108: Error executing lua vim/shared.lua:64: s: expected string, got nil
stack traceback:
        vim/shared.lua:64: in function 'gsplit'
        vim/shared.lua:111: in function 'split'
        /home/xx/.config/nvim/plugged/scnvim/lua/scnvim/install.lua:14: in function 'ge
t_scnvim_root_dir'
        /home/xx/.config/nvim/plugged/scnvim/lua/scnvim/install.lua:32: in main chunk
        [C]: in function 'require'
        [string ":lua"]:1: in main chunk
```
I tried removing manually the symlink in my `Extensions` dir, but didn't help.

**Expected behavior**

**Steps to reproduce**

:PlugUpdate

**Additional context**

**Information**
- `nvim --version`: 
```
NVIM v0.5.0-812-gd17e50879
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-5 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-317a2489-aba5-414a-b9f3-9551746c326c

Features: +acl +iconv +tui
See ":help feature-compile"

system vimrc file: "$VIM/sysinit.vim"
fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```
- Operating system: Arch Linux 
- Running scnvim in a Terminal/GUI: terminal

**Comment by davidgranstrom** [comment]
Thanks for the report. Could you post the output from this command?

```
:lua print(package.searchpath('scnvim', package.path))
```

**Comment by kflak** [comment]
Starting to suspect something is up with Lua in general...:

```
nil
^Ino file './scnvim.lua'
^Ino file '/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/share/luajit-2.1.0-beta3/scnvim.lua'
^Ino file '/usr/local/share/lua/5.1/scnvim.lua'
^Ino file '/usr/local/share/lua/5.1/scnvim/init.lua'
^Ino file '/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/share/lua/5.1/scnvim.lua'
^Ino file '/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/share/lua/5.1/scnvim/init.lua'
```

**Comment by davidgranstrom** [comment]
@kflak Hmm, I get similar output if I try the command with `package.searchpath('foobar' ..`. So maybe this is not a reliable way to get the path to the scnvim plugin. I have a vague recollection that there has been some work on nvim 0.5 in regards to lua and rtp so maybe something has changed upstream recently.

**Comment by madskjeldgaard** [comment]
It works fine on Nvim 0.5 here with Packer.nvim

**Comment by davidgranstrom** [comment]
@kflak Could you please provide the output of this command if you have the time?

```
:echo nvim_get_runtime_file('lua/scnvim.lua', v:true)
```

**Comment by kflak** [comment]
I'm getting this:
```
[]
```
A bit more context: when cd-ing into `~/.config/nvim/plugged/scnvim/lua` and running 
```
:lua print(package.searchpath('scnvim', package.path))
```
I get the output:
```
./scnvim.lua
```
Also, if I then run 
```
scnvim#install()
``` 
in the same dir, I get a different error:
```
Error detected while processing function scnvim#install:
line    1:
E5108: Error executing lua [string ":lua"]:1: loop or previous error loading module 'scnvim/install'
```

**Comment by kflak** [comment]
Oh, when I run 
```
:echo nvim_get_runtime_file('lua/scnvim.lua', v:true)
``` _inside_ the plugged dir I get:
```
['/home/xx/.config/nvim/plugged/scnvim/lua/scnvim.lua']
```

**Comment by davidgranstrom** [comment]
@kflak Thanks for the info! I will have to do some testing locally and try to get to the bottom of this. In essence, I need to get the path (reliably) of the plugin in the installation step in order to create the symbolic link to `scide_scnvim` using the post-install hook. I'm just curious, if you install the plugin without providing the post-install hook to vim-plug and then run `:call scnvim#install()` from the command line (after `:PlugInstall`), do you still get the same error as before that the path is `nil`?

**Comment by kflak** [comment]
Same same when doing it that way...

**Comment by davidgranstrom** [comment]
Okay, thanks. That is very helpful in order to continue debugging this! Did you recently update `nvim` btw?

**Comment by kflak** [comment]
Yup. Today :-)

**Comment by kflak** [comment]
One more bit of context: I get the same error as before when installing through packer.nvim: 
```
Error detected while processing function scnvim#install:
line    1:
E5108: Error executing lua vim/shared.lua:64: s: expected string, got nil
stack traceback:
        vim/shared.lua:64: in function 'gsplit'
        vim/shared.lua:111: in function 'split'
        ...vim/site/pack/packer/start/scnvim/lua/scnvim/install.lua:14: in function 'get_scnvim_root_dir'
        ...vim/site/pack/packer/start/scnvim/lua/scnvim/install.lua:32: in main chunk
        [C]: in function 'require'
        [string ":lua"]:1: in main chunk
```

**Comment by kflak** [comment]
In the meanwhile it works fine just to symlink the scnvim classes...

**Comment by salkin-mada** [comment]
> It works fine on Nvim 0.5 here with Packer.nvim

NVIM v0.5.0
Lua 5.4.1 

Yes it did. And on a machine using `packer.nvim` it looks like it is still working - but that is only if the "install call" was done before some change. not sure what changed though? 
so if the symlink already exists it will work. but delete it and the issue is there.
today using my dotfiles on a different machine i get the following ( using packer- >`use {'davidgranstrom/scnvim'}` and then manually `:call scnvim#install()` )
![scrn-2020-11-09-17-06-43](https://user-images.githubusercontent.com/12082586/98565831-5b848f00-22ae-11eb-8f9c-e72f9a8eb266.png)

same a @kflak 

+ yes, manually symlinking the classes works.

also using the earlier working post install command with `packer.nvim` now fails on a "fresh" system. because of the same issue. :+1:

**Comment by madskjeldgaard** [comment]
I actually don't think the new (and very cool) install function ever worked for me. Maybe this is a linux issue somehow since the three of us use that?

**Comment by salkin-mada** [comment]
I am pretty sure it did. When i ported from `vim-plug` to `packer.nvim` two weeks ago. I uninstalled `scnvim` via `vim-plug` and removed the symlink pointing to `.vim/plugged-etc.etc.`. And after installing `scnvim` with `packer.nvim` i ended up with a new a beautiful symlink in my Extensions folder pointing to `$HOME/.local/share/nvim/site/pack/packer/start/scnvim/scide_scnvim` on my laptop.
today on my desktop i had to create this manually.

**Comment by salkin-mada** [comment]
but my memory is a vague and transformative thing..

**Comment by davidgranstrom** [comment]
Thanks for all the info! I was able to repro this on my linux machine with the latest nvim appimage. Something seem to have changed in `nvim` in regards to how `package.path` is populated, at least on linux.. anyways, I hope that #131 will resolve this. I've tested with manjaro linux and also on macOS, will test on windows tomorrow. Please try out the new PR if you have the time!

**Comment by davidgranstrom** [comment]
Confirmed that installation also works on windows, so I'm merging #131, but please feel free to reopen this issue if the problem still persist!
