### ISSUE TITLE
[BUG] <Plug> commands don't register with non-recursive mapping

### ISSUE THREAD

**Issue by daveriedstra** [davidgranstrom/scnvim#133]
**Describe the bug**
The `<Plug>` commands don't work with non-recursive mapping (eg, `nnoremap` instead of `nmap`), eg 
```
nmap <leader><CR> <Plug>(scnvim-send-block)
``` 
will register, but 
```
nnoremap <leader><CR> <Plug>(scnvim-send-block)
```
will not.

**Expected behavior**
non-recursive mappings should work

**Steps to reproduce**
1. with a working scnvim setup, add `nnoremap <leader><CR> <Plug>(scnvim-send-block)` to .vimrc / vim config file
2. save and source the new config
3. open a supercollider file
4. start scnvim (eg `:SCNvimStart`)
5. try to send a line with `<leader><CR>`
6. note that it fails

**Additional context**
* **workaround:** use `nmap` instead
* (this might be a misunderstanding on my part of how these are supposed to work in vim in general; in which case maybe a reminder on the readme would save future users some time)

**Information**
- `nvim --version`:
```
NVIM v0.4.4
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-u4YhjF/neovim-0.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim-u4YhjF/neovim-0.4.4/build/config -I/build/neovim-u4YhjF/neovim-0.4.4/src -I/usr/include -I/usr/include/lua5.1 -I/build/neovim-u4YhjF/neovim-0.4.4/build/src/nvim/auto -I/build/neovim-u4YhjF/neovim-0.4.4/build/include
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
- Operating system: Pop!_OS 20.10
- Running scnvim in a Terminal/GUI: terminal nvim

**Comment by davidgranstrom** [comment]
@daveriedstra Hi -

Yes, as you've noticed the correct way of using `<Plug>` mappings in nvim is by mapping them recursively (e.g. using `nmap` instead of `nnoremap`), this is because the `rhs` of the mapping needs to be expanded in order for it to perform the intended action specified by the plugin. I can see why this might be confusing, so I'll add a note about it in the readme per your suggestion. Thanks!
