### ISSUE TITLE
[BUG] Windows 10, GUI elements do not load

### ISSUE THREAD

**Issue by usrfriendly** [davidgranstrom/scnvim#138]
**Describe the bug**
Gui elements, such as Quarks.Gui or server.scope do not load in Windows when I first start SCNvimStart and boot the server.

**Expected behavior**
Running Quarks.gui or Server.scope should produce the corresponding window with the default configuration

**Steps to reproduce**
Open a Supercollider file, run SCNvimStart,, evaluate a line with `Quarks.gui;`

or

Open a Supercollider file, run SCNvimStart, booth the server, evaluate a line that reads `server.scope;`

**Additional context**
It works OOTB on my Debian Bullseye install running nvim 0.4.4, TUI and QT, but not in Windows 10.

SCNvimHelp spawns the help window.  *After* I do this, I can open all GUI elements, but they should be able to open without me having to open the Help window first.

**Information**
- `0.4.4` and `0.5.0-dev+1114-g0c76cf9`:
- Operating system: Windows
-Tested: Terminal UI, QT, FVim Frontend in Win10

**Comment by davidgranstrom** [comment]
@usrfriendly Thanks for the report. Unfortunately scnvim does not have any control over this (it only forwards commands to the sclang executable via stdin) so I'm guessing that this behaviour is something you would also experience when using the `sclang` executable directly from the command line (using the default readline interface). 

I would suggest that you try and reproduce the bug using the `sclang` executable from the command line if possible, and if it can be reproduced create an issue on the main SuperCollider repo on github.

**Comment by davidgranstrom** [comment]
Closing this for now.
