### ISSUE TITLE
[Question]:  Return sometimes not toggling postwindow

### ISSUE THREAD

**Issue by paum3** [davidgranstrom/scnvim#142]
Hi,

It happens really sometimes, and only with some .scd files what is strange, and I can't understand what is going on but what acctualy happens if I want to toggle post window is that neovim runs another command - in my case it is LF file manager in floatterm.

When I close nvim and open some other .scd file, everything works -> return key toggles post window, key shortcut for LF file manager runs, LF in floatterm.

What looks weird for me is that it happens only with some .scd files. 

Sorry about this post, I know it is maybe not really related to scnvim.

Thank you for your work.
paum

**Comment by davidgranstrom** [comment]
Could it be a conflicting mapping for `scnvim-postwindow-toggle` perhaps? 

Check the output of:
```vim
:verbose nnoremap <CR>
```
First directly after starting nvim, then after opening a `.scd` file, and check again if it the mapping stops working to see if some other plugin is overriding the mapping.

**Comment by paum3** [comment]
clear start:   No mapping found.
with scd file opened:
n  <CR>         @<Plug>(scnvim-postwindow-toggle)

I don't understand. It is happening only in one folder. I think it is nvim
problem.

**Comment by davidgranstrom** [comment]
@paum3 I don't know if you are still experiencing this issue, but maybe it could be related to #147?

**Comment by paum3** [comment]
After updating to new versions, this issue is no longer here. I am closing this. Thank you
