### ISSUE TITLE
[BUG] Error when opening .scd file

### ISSUE THREAD

**Issue by emuhr** [davidgranstrom/scnvim#154]
**Describe the bug**
I'm receiving this error right after opening a .scd file:

```
Error detected while processing function scnvim#document#set_current_path[1]..scnvim#sclang#is_running:
line    1:
E5108: Error executing lua [string "luaeval()"]:1: attempt to index a boolean value
E5108: Error executing lua [string "luaeval()"]:1: attempt to index a boolean value
```

Executing a SCN command e.g. `SCNvimStart` gives me a similar error:
```
Error detected while processing function scnvim#sclang#open:
line    1:
E5108: Error executing lua [string ":lua"]:1: attempt to index a boolean value
```

**Additional context**
I'm using Packer.nvim with the following stripped down config:
```
return require('packer').startup(function()
  use 'wbthomason/packer.nvim'
  use {'davidgranstrom/scnvim', run = ':call scnvim#install()'}
end)
```
The scide_scnvim symlink is correct.

I also deleted `~/.local/share/nvim` and did the setup again without success.

Running `checkhealth scnvim` gives me:
```
health#scnvim#check
========================================================================
## scnvim
  - OK: SCNvim classes installed: /home/xxx/.local/share/SuperCollider/Extensions/scide_scnvim
  - OK: has("timers") - success
  - INFO: sclang executable: /usr/bin/sclang
  - INFO: using g:scnvim_scdoc_render_prg = /usr/bin/pandoc
  - INFO: using g:scnvim_scdoc_render_args = % --from html --to plain -o %
```

**Information**
- `nvim --version`:
```
NVIM v0.5.1
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim/src/neovim-0.5.1/build/config -I/build/neovim/src/neovim-0.5.1/src -I/usr/include -I/build/neovim/src/neovim-0.5.1/build/src/nvim/auto -I/build/neovim/src/neovim-0.5.1/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

- Operating system: Arch Linux with kernel 5.15.2-arch1-1
- Running scnvim in a Terminal/GUI: Terminal

I'm kind of lost what to do next. Am I missing something crucial?

**Comment by davidgranstrom** [comment]
@emuhr Thanks for the report. I cannot recreate the behaviour you've encountered, do you have your complete nvim configuration available online? I would need to see more context in order to debug this.

**Comment by emuhr** [comment]
@davidgranstrom Heres my current neovim configuration: https://github.com/emuhr/neovim
It's a WIP as I'm currently migrating to LUA. So there could be an obvious error I made or something I missed.
Thanks for looking into this.

**Comment by davidgranstrom** [comment]
Thanks! I think the issue is that you are currently putting all of your config files directly inside the top-level `lua` directory, which means that the file `scnvim.lua` (that contiains your mappings) will be required before the actual `scnvim` module. It is encouraged (at least to my knowledge) to namespace your personal lua config files in some way, either by using a prefix in the actual filename, or maybe easier by just putting all the files in a namespace directory e.g. `lua/emuhr/`

**Comment by davidgranstrom** [comment]
I'm not using a lua only config at the moment, but I'm using the namespace idea for the parts of my config which is lua based: https://github.com/davidgranstrom/vim-conf/tree/master/lua/dkg

**Comment by emuhr** [comment]
Hey @davidgranstrom, thank you for the tip. That was exaxtly the cause. After putting everything in a namespace (thanks to your example) scnvim works as expected.
This issue can be closed :)

**Comment by emuhr** [comment]
The use of namespaces to prevent clashes is mentioned in this guide: https://github.com/nanotee/nvim-lua-guide#tips
