### ISSUE TITLE
[Question]: how do you guys record your music?

### ISSUE THREAD

**Issue by molleweide** [davidgranstrom/scnvim#157]
Hi there, 

I just wanted to ask how you guys are recording your music ? Is anyone here recording to Reaper or
using scnvim as a synth or audio generator tool for production in Reaper? Myself I am a newbie when it comes to 
supercollider but I would like to try to use scnvim and use it a a synth for my music production in Reaper.

**Comment by davidgranstrom** [comment]
Hi @molleweide!

That is an interesting discussion for sure! I also use Reaper and have some different workflows for working with SuperCollider depending on what I want to achieve. I don't have the time to write something up at the moment but I would gladly take part of the discussion later.

PS. I think this would probably get more attention on either https://scsynth.org or by opening a new discussion [here](https://github.com/davidgranstrom/scnvim/discussions)

**Comment by molleweide** [comment]
Thanks for replying David!

I will be checking out the forum for sure and get back here when I have familiarized myself a bit more with scnvim. This is awesome!!
