### ISSUE TITLE
[FR] Allow precompiling all help files

### ISSUE THREAD

**Issue by madskjeldgaard** [davidgranstrom/scnvim#177]
Hello

One thing that I would love to be able to do is to fuzzy search the _text_ of the help files on the system. Preferably using the compiled .txt files made by scnvim, but as it is right now, as far as I understand, they are compiled lazily when needed. If there was a lua function that would (re)compile all help files, using RipGrep we could easily search the contents of all the files instead of only the titles/classes as we do now in both fzf-sc and in the telescope plugin.

**Comment by davidgranstrom** [comment]
@madskjeldgaard I've implemented this in the linked PR, please try it out whenever you have the time!

```lua
:lua require'scnvim.help'.render_all()
```
The function accepts a callback as its first argument if you want to do something after conversion has been completed. One limitation is that only works with `pandoc` at the moment (with hardcoded arguments). This will change as soon as #153 is ready.
