### ISSUE TITLE
lua-config: mapping for SCNvimRecompile?

### ISSUE THREAD

**Issue by kflak** [davidgranstrom/scnvim#186]
I usually have `<F4>` mapped to `:SCNvimRecompile` and try to recreate this in the new config, but am not successful. How would I go about setting this?

**Comment by kflak** [comment]
additionally it would be nice to know how to map any command in the new system... I have these kind of monsters lurking in my basement that would be great to keep in one place:
```
{'n', '<F8>', [[<cmd>lua require'scnvim'.send('if(s.isRecording){s.stopRecording}{s.record("rec"+/+Git(thisProcess.nowExecutingPath.dirname).sha[0..5]++"_"++Date.localtime.stamp++".wav", numChannels: s.options.numOutputBusChannels)}')<CR>]] }
```

**Comment by davidgranstrom** [comment]
The `mappings` table in the config is a convenience to map the functions exported by the [`editor` module](https://davidgranstrom.github.io/scnvim/modules/scnvim.editor.html), basically the parts of the API that doesn't have a user command abstraction.

To map `:SCNvimRecompile` you could either map the command as you have done before, or map the lua function: 

```
vim.keymap.set('n', '<leader>sk', '<cmd>lua require"scnvim".recompile()<cr>')
```


It is also possible to not specify any mappings in the `mappings` table of the config, and set up your own keymaps:

```
vim.keymap.set({'n', 'i'}, '<C-e>', '<cmd>lua require"scnvim.editor".send_block()<cr>')
```

(note: I will make the eval flash effect default to `true`, which is not the case at the moment when you set up mappings manually like the example above.)

**Comment by davidgranstrom** [comment]
Maybe the `scnvim.map` helper could take a function as well, that would consolidate all mappings to the config.

**Comment by kflak** [comment]
That would be really nice!

**Comment by davidgranstrom** [comment]
Its now possible to map arbitrary functions:

```lua
    ['<leader>sk'] = scnvim.map(scnvim.recompile), -- no need to wrap
    ['<F5>'] = scnvim.map(function()
      vim.cmd [[ SCNvimGenerateAssets ]]
    end),
```

**Comment by kflak** [comment]
Fantastic!
