### ISSUE TITLE
[FR] resize floating post window

### ISSUE THREAD

**Issue by kflak** [davidgranstrom/scnvim#187]
I love the new floating post window, but it's just a bit too small for my taste, and I don't see any config option to change this. Is it possible that the post.size parameter would apply to the post window as well?

**Comment by davidgranstrom** [comment]
You can use `postwin.config.width` and `postwin.config.height` at the moment, but I think I'll add `postwin.size = {width, height}` as a convenience. 

You can see all options for `config` in `:h nvim_open_win` if you want to override the default settings.

**Comment by davidgranstrom** [comment]
Great to hear! Yes, that's correct. Hmm, might rename `offset_{x,y}` to `{row,col}_offset` to make that a bit clearer actually.

**Comment by davidgranstrom** [comment]
I've refactored the floating post window configuration. It's now possible to set `width` and `height` in the "top level" of the config as well as `row` and `col`, see an example [here](https://github.com/davidgranstrom/scnvim/issues/183#issuecomment-1144125266).
