### ISSUE TITLE
[BUG] mul_add = false not respected for luasnip generation

### ISSUE THREAD

**Issue by kflak** [davidgranstrom/scnvim#189]
Setting the `snippets.mul_add` config value to `false`has no effect on the generated snippets. I may just be doing the setup wrong, of course...

**Steps to reproduce**

Set configuration to:
```    snippet = {
        engine = {
            name = 'luasnip',
        },
        mul_add = false
    }
```
Run `:SCNvimGenerateAssets`.

Configure `nvim-cmp` to use the generated snippets;
```
require("luasnip").add_snippets("supercollider", require("scnvim/utils").get_snippets())
```

**Information**

- Operating system

Arch Linux 5.15.36.41.realtime1-2-rt-lts

- SuperCollider version

- `nvim --version`

```
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser
```

- Package manager

packer.nvim

**Comment by davidgranstrom** [comment]
Sorry, it is currently not supported. It's there as a placeholder on the refactor branch. I'll see if it makes it into that PR or if it will be implemented as a follow up!
