### ISSUE TITLE
[BUG] Installed successfully, but none of the commands are working

### ISSUE THREAD

**Issue by bla9kdog** [davidgranstrom/scnvim#192]
**Describe the bug**
After installing SCNvim, none of the commands are showing up.

For example: if I type :SCNVimStart, I get an error saying it's not an editor command. I've tried this in both *.sc and *.scd files.

Here's the checkhealth output:

```
scnvim: health#scnvim#check
========================================================================
## scnvim
  - OK: SCNvim classes installed: /home/me/.local/share/SuperCollider/Extensions/scide_scnvim
  - OK: has("timers") - success
  - INFO: using g:scnvim_sclang_executable = /usr/bin/sclang
  - INFO: sclang executable: /usr/bin/sclang
  - INFO: Could not find scdoc render program. See :help |scnvim-help-system| for more information.
    This is an optional dependency and only needed for SCDoc integration.
```

**Expected behavior**
:SCNVim* commands should show up.

**Information**

- Operating system
Arch Linux

- SuperCollider version
3.12.2

- `nvim --version`
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3

- Package manager
vim-plug

**Comment by ranjithshegde** [comment]
> For example: if I type :SCNVimStart, I get an error saying it's not an editor command. I've tried this in both *.sc and *.scd files.

Not sure if its your typo in the error report or also in your trial, but `SCNV...` is not the command. `SCNvim...` is. The `V` is not capitalized

**Comment by bla9kdog** [comment]
> That sounds strange indeed. You could try :lua require'scnvim'.start() and see if that works. :SCNvimStart is just a wrapper for that function call.

If I type this, I get the post window. But none of the keybindings work. I'll check the other branch. Thanks!

```
compiling class library...
	Found 867 primitives.
	Compiling directory '/usr/share/SuperCollider/SCClassLibrary'
	Compiling directory '/usr/share/SuperCollider/Extensions'
	Compiling directory '/home/me/.local/share/SuperCollider/Extensions'
	numentries = 1283639 / 19422096 = 0.066
	5736 method selectors, 3386 classes
	method table size 20834432 bytes, big table size 155376768
	Number of Symbols 14965
	Byte Code Size 450281
	compiled 559 files in 0.57 seconds
Info: 4 methods are currently overwritten by extensions. To see which, execute:
MethodOverride.printAll
compile done
localhost : setting clientID to 1.
internal : setting clientID to 1.
Class tree inited in 1.01 seconds
*** Welcome to SuperCollider 4.13.0-dev. *** For help type ctrl-c ctrl-h (Emacs) or :SChelp (vim) or ctrl-U (sced/gedit).
```

> Not sure if its your typo in the error report or also in your trial, but SCNV... is not the command. SCNvim... is. The V is not capitalized

Oops, this was just a typo in the bug report. :) Thanks

**Comment by bla9kdog** [comment]
Ok, I found the culprit, "vim-polyglot" was causing issues. If I remove it, SCNvim works fine.

It's weird because it happens only on my Linux machine. Works fine on MacOS.

**Comment by riordant** [comment]
Sorry to reopen this but I am getting the exact same bug. None of the editor commands work, but it is installed correctly.

Information

Operating system
Linux Mint

`supernova --version`
supernova 3.14.0-dev (Built from branch 'develop' [6d65a5877])

`nvim --version`:
NVIM v0.9.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

Package manager
vim-plug

`checkhealth` output:
```
scnvim: require("scnvim.health").check()

scnvim ~
- OK nvim version 0.9.0
- OK sclang executable: /usr/local/bin/sclang
- OK scnvim classes are installed: /home/riordant/.local/share/SuperCollider/Extensions/scide_scnvim
- OK keymaps are defined
```

I've reverted to the most basis `init.lua` possible:

```
local call = vim.call
local cmd = vim.cmd
local Plug = vim.fn['plug#']
local PATH = "~/.nvim/plugged" --You can use any PATH which you prefer

call('plug#begin', PATH)
        Plug 'davidgranstrom/scnvim'
call'plug#end'

local scnvim = require 'scnvim'
scnvim.setup({})
```

and it still doesn't pick up the editor commands.

@davidgranstrom any ideas? thanks
