### ISSUE TITLE
[FR]: optional use tmux instead of vim terminal

### ISSUE THREAD

**Issue by grammoboy2** [davidgranstrom/scnvim#193]
**Is your feature request related to a problem? Please describe.**

In vim-arduino it's possible to set tmux instead of the vim terminal (via vim-slime), is that possible with scnvim as well?
https://github.com/stevearc/vim-arduino

I think I would prefer such a worklow. If one is familiar with tmux and not with vim terminal, it's working easier with it. (resizing, panes, zoom etc.)

**Comment by davidgranstrom** [comment]
It is currently not supported, but it might be a good candidate for a future scnvim extension (see #153, the API would need some slight adjustments to make it possible though)

A side note, scnvim does not actually use `:terminal` but a regular buffer for the post window output.

**Comment by grammoboy2** [comment]
FYI: 
https://github.com/tidalcycles/vim-tidal from @munshkr et. al.
seems to use tmux by default.

**Comment by davidgranstrom** [comment]
@grammoboy2 Hi,

I wrote a scnvim extension for this, you can find it here: https://github.com/davidgranstrom/scnvim-tmux
