### ISSUE TITLE
[BUG] viewing help with pandoc throws ERROR: Message 'getHelpUri' not understood

### ISSUE THREAD

**Issue by cdbzb** [davidgranstrom/scnvim#195]
Greetings 

when trying to view help using pandoc I get the error below (help using the help browser works fine and checkhealth is OK):
nvim 0.8 Mac Big Sur most recent scnvim installed via plugged

```
ERROR: Message 'getHelpUri' not understood.
RECEIVER:
class SCNvim (0x7fb55e8866c0) {
  instance variables [19]
    name : Symbol 'SCNvim'
    nextclass : instance of Meta_SCNvimDoc (0x7fb55ca48000, size=19, set=5)
    superclass : Symbol 'Object'
    subclasses : nil
    methods : nil
    instVarNames : nil
    classVarNames : instance of SymbolArray (0x7fb55e886840, size=3, set=2)
    iprototype : nil
    cprototype : instance of Array (0x7fb55e886900, size=3, set=2)
    constNames : nil
    constValues : nil
    instanceFormat : Integer 0
    instanceFlags : Integer 0
    classIndex : Integer 382
    classFlags : Integer 0
    maxSubclassIndex : Integer 382
    filenameSymbol : Symbol '/Users/michael/Library/Application Support/SuperCollider/Extensions/scide_scnvim/Classes/SCNvim.sc'
    charPos : Integer 0
    classVarIndex : Integer 765
}
ARGS:
Instance of String {    (0x7fb539f5a1b8, gc=58, fmt=07, flg=10, set=02)
  indexed slots [8]
      0 : M
      1 : o
      2 : n
      3 : i
      4 : t
      5 : o
      6 : r
      7 : s
}
CALL STACK:
	DoesNotUnderstandError:reportError
		arg this = <instance of DoesNotUnderstandError>
	Nil:handleError
		arg this = nil
		arg error = <instance of DoesNotUnderstandError>
	Thread:handleError
		arg this = <instance of Thread>
		arg error = <instance of DoesNotUnderstandError>
	Object:throw
		arg this = <instance of DoesNotUnderstandError>
	Object:doesNotUnderstand
		arg this = <instance of Meta_SCNvim>
		arg selector = 'getHelpUri'
		arg args = [*1]
	Meta_SCNvim:eval
		arg this = <instance of Meta_SCNvim>
		arg expr = "SCNvim.getHelpUri("Monitors")"
		arg callback_id = "1"
		var result = nil
	Process:interpretCmdLine
		arg this = <instance of Main>
^^ ERROR: Message 'getHelpUri' not understood.
RECEIVER: SCNvim
```

**Comment by cdbzb** [comment]
Possibly related I am receiving "Error no tags file" when I try to view source for an Object in the editor.

SCNvimGenerateAssets throws the following error

ERROR: Primitive '_FileWrite' failed.
Failed.
RECEIVER:
Instance of File {    (0x7ff7f36b24e8, gc=58, fmt=00, flg=00, set=02)
  instance variables [1]
    fileptr : nil
}
CALL STACK:
	MethodError:reportError
		arg this = <instance of PrimitiveFailedError>
	Nil:handleError
		arg this = nil
		arg error = <instance of PrimitiveFailedError>
	Thread:handleError
		arg this = <instance of Thread>
		arg error = <instance of PrimitiveFailedError>
	Thread:handleError
		arg this = <instance of Routine>
		arg error = <instance of PrimitiveFailedError>
	Object:throw
		arg this = <instance of PrimitiveFailedError>
	Object:primitiveFailed
		arg this = <instance of File>
	Meta_SCNvim:generateTags
		arg this = <instance of Meta_SCNvim>
		arg outputPath = "/Users/michael/.cache/nvim/s..."
		var tagPath = "/Users/michael/.cache/nvim/s..."
		var tagFile = <instance of File>
		var tags = [*0]
	< FunctionDef in Method Meta_SCNvim:generateAssets >  (no arguments or variables)
	Routine:prStart
		arg this = <instance of Routine>
		arg inval = 7.745185418
^^ The preceding error dump is for ERROR: Primitive '_FileWrite' failed.
Failed.
RECEIVER: a File

**Comment by davidgranstrom** [comment]
@cdbzb Thanks for the report. It looks like the `SCNvim` classes might be out-of-date based on the output from the first error. Perhaps try `:lua require'scnvim.install'.uninstall()` or manually deleting the link at `/Users/michael/Library/Application Support/SuperCollider/Extensions/scide_scnvim` in case there is some kind of conflict from an older install. The classes will be linked automatically the next time you call `scnvim.setup`.

**Comment by cdbzb** [comment]
Thanks for the speedy reply! (and for this lifesaving project!)

Tags are back and I no longer get the error...

Still no help with pandoc though! I get the "SCDoc indexing help files" and check health still OK ` { "$1", "--from", "html", "--to", "plain", "-o", "$2" }` then silence.

SCNvimHelp("Pseq") returns "no results for "Pseq""

any other thoughts?

**Comment by cdbzb** [comment]
Thanks! I had actual files rather than links in the Classes folder. and thanks for this amazing project

**Comment by daveriedstra** [comment]
> @cdbzb Thanks for the report. It looks like the `SCNvim` classes might be out-of-date based on the output from the first error. Perhaps try `:lua require'scnvim.install'.uninstall()` or manually deleting the link at `/Users/michael/Library/Application Support/SuperCollider/Extensions/scide_scnvim` in case there is some kind of conflict from an older install. The classes will be linked automatically the next time you call `scnvim.setup`.

This just cleared up a host of issues I ran into after upgrading to the new config and might be worth mentioning on the migration page in the wiki if there are no potential unsavoury side-effects.
