### ISSUE TITLE
[BUG] SCNvim crashes out of Neovim from too fast input. 

### ISSUE THREAD

**Issue by vsandstrom** [davidgranstrom/scnvim#228]
**Describe the bug**
When neovim or scnvim gets too much input, either as keypresses ( like traversing the page holding down 'j' ) or posting text to post-window really fast, like midi input values from several fader, neovim crashes.  

**Expected behavior**
To navigate around without  being thrown out to the command line. 

**Steps to reproduce**
unknown

**Additional context**
I have configured wait time for new key input to be faster, as similar to this:
```bash
defaults write -g InitialKeyRepeat -int 15;
defaults write -g KeyRepeat -int 1
```
I sometime get weird errors when just passing a line of code with the cursor, as if it tries to execute that line.
I also sometimes get errors when a comment is in the middle of a block, that the interpreter does not recognize  as non-runnable code and tries to execute, but can't.

**Information**

- Operating system
macOS 13.5.1

- SuperCollider version
3.13.0

- `nvim --version`
It is the same on both the "stable" 9.4 version and the "HEAD" version 10 >=<br>
installed using homebrew

- Package manager
Packer.nvim
scnvim config here:<br>
https://github.com/vsandstrom/.dotfiles/blob/main/nvim/lua/config/supercollider.lua
https://github.com/vsandstrom/.dotfiles/blob/main/nvim/after/ftplugin/supercollider.lua

**Comment by davidgranstrom** [comment]
Thanks for the report. Do you by chance have access to the crash report? If `nvim` crashed there should be log file accessable in the `Console.app`. Without a log this issue might be tricky to debug until we can find a way to reproduce it.

**Comment by vsandstrom** [comment]
These were the ones I could find, there were no neovim crash reports, and I cannot make sense of these to know what they are about. The dates does correspont to some of the issues.
I will have to stress test neovim/scnvim to get a fresh crash.

[scsynth-2023-10-23-004503.log](https://github.com/davidgranstrom/scnvim/files/13195951/scsynth-2023-10-23-004503.log)
[scsynth-2023-10-26-130312.log](https://github.com/davidgranstrom/scnvim/files/13195952/scsynth-2023-10-26-130312.log)

**Comment by vsandstrom** [comment]
I tried to find a crash report after crashing it on purpose but there is none, seems nvim crashes silently. 

This is how it looks. There might be audio here as well.

https://github.com/davidgranstrom/scnvim/assets/79695983/31cd6c5d-c8f8-4dc2-9690-f3872e6d3113

**Comment by vsandstrom** [comment]
I've turned off all of my other plugins and turned them on again, and I am suspicious of a plugin called [markdown-preview.nvim](https://github.com/iamcco/markdown-preview.nvim). Ill try running without that for a while.

**Comment by davidgranstrom** [comment]
@vsandstrom Thanks for the logs. However, they seem to indicate a crash report/log of `scsynth` (that in itself should not bring down the `nvim` process). Did you find them in Console.app under the "Crash reports" section? I might have been a bit to unspecific in my previous message when I asked for the logs, the reports that would be of interest would be under the "Crash Reports" tab in Console.app.

Looking at the video, it does not look like much input to me (the navigation). But maybe there is some MIDI input also that is not shown in video? I tried to create a "stress test" that logs a lot to the post window since you mentioned this might be related in your initial report. Are you able to crash `nvim` using this code? Please feel free to tweak the parameters. I was not able to crash the process or even notice any degradation of keyboard input while running this.

```supercollider
(
var waitTime = 1/120;
var numParallel = 8;
numParallel.do {arg n;
    Routine.run {
        inf.do {arg i;
            var offset = rrand(-1e-3, 1e-3);
            "N: % iter: % offset: %".format(n, i, offset).postln;
            (waitTime - offset).wait;
        }
    };
};
)
```

Also, are you using `treesitter` for `supercollider` syntax highlighting? You could experiment with turning syntax highlighting off (also for the post window) and see if you can still reproduce the crash like in your video.

**Comment by vsandstrom** [comment]
There were no crash logs for Neovim in the Console.app crash report tap. I only found these scsynth crash logs there, but I guess they do not really matter in this case, sorry about that. 

The example you sent me does indeed crash neovim, with and without treesitter enabled. In the video that I sent, I had no input other than the built-in keyboard navigating up and down. The same with your example, but it will crash by itself around 800-1100 iterations either way, moving around just does it faster.

**Comment by davidgranstrom** [comment]
Thanks for testing, and good (under the circumstances) that we've found a way to reproduce the crash! I think the next step would be to disable every plugin except for scnvim and run the test again. Since I can't make the crash happen on my machine something between our setups must be differ.

**Comment by vsandstrom** [comment]
I have tried to turn all plugins on and off, but without any result. Probably missed something, but since my setup made it difficult to test, I tried migrating to Lazy from Packer, just as I was restructuring everything anyway. 

It resulted in a new message I've not seen before, see pic. The bottom half of the term window that has been cropped is the regular command input prompt.
<img width="1680" alt="Skärmavbild 2023-11-09 kl  11 43 26 -  :Homebrew:neovim--git:src:nvim:msgpack_rpc:unpacker c" src="https://github.com/davidgranstrom/scnvim/assets/79695983/b4cf19d7-a3a6-4e71-aaba-c006215c01b6">

It seems to exit on the assert in the function unpacker_parse_redraw in the file unpacker.c which on my mac device is located at ```~/Downloads/neovim-stable/src/nvim/msgpack_rpc/```
Maybe this makes sense to you?

I will do another run through the plugins as well.

**Comment by vsandstrom** [comment]
[nvim-2023-11-16-101359.txt](https://github.com/davidgranstrom/scnvim/files/13376647/nvim-2023-11-16-101359.txt)
[nvim-2023-11-10-093412.txt](https://github.com/davidgranstrom/scnvim/files/13376648/nvim-2023-11-10-093412.txt)

**Comment by davidgranstrom** [comment]
Thanks for the logs! Do you have any "remote plugins" installed at the moment? You can check this if you run `:UpdateRemotePlugins` and then inspecting the file found at that path.

**Comment by vsandstrom** [comment]
running ```:UpdateRemotePlugins``` returns "not an editor command". 

the result of ```cat ~/.local/share/nvim/rplugins.vim``` returns:
```bash
" perl plugins


" node plugins


" python3 plugins


" ruby plugins


" python plugins
```

**Comment by davidgranstrom** [comment]
Thanks for verifying. I've written a new test to simulate what's happening when printing to the post window, could you please confirm if this also causes a crash or not?

```lua
local uv = vim.loop

local counter = 1
local max_count = 2000
local rate = math.floor(1000 / 300)

local buf = vim.api.nvim_create_buf(true, true)
local id = vim.api.nvim_open_win(buf, false, {
  relative = 'editor',
  anchor = 'NE',
  row = 0,
  col = vim.o.columns,
  width = 40,
  height = 20,
  border = 'single',
  style = 'minimal',
})

local timer = uv.new_timer()
local draw_fn = function()
  local line = string.format('counter: %d', counter)
  vim.api.nvim_buf_set_lines(buf, -1, -1, true, { line })
  local num_lines = vim.api.nvim_buf_line_count(buf)
  vim.api.nvim_win_set_cursor(id, { num_lines, 0 })
  if counter == max_count then
    timer:stop()
    vim.api.nvim_win_close(id, true)
  end
  counter = counter + 1
end
timer:start(rate, rate, vim.schedule_wrap(draw_fn))
```

**Instructions**

1. `nvim /tmp/redraw.lua`
2. Paste the code above into the new file and save.
3. `:so%`

**Expected**

You should see a floating window appear on the right side of the editor printing the count, it will close when the count has reached `max_count`. Please feel free to adjust the parameters for the test.

**Comment by vsandstrom** [comment]
This does not crash, even with faster rate and higher max_count. It seems this is very stable.

**Comment by davidgranstrom** [comment]
Thanks for the confirmation. It might be a different code path that triggers the crash then. Looking at the log files you provided, perhaps the `invoke_read_cb` called indirectly by libuv needs to be involved.

This issue has now shifted into debugging Neovim internals, and I think a proper core dump is needed to continue investigation at least on my end since I cannot reproduce the crash. If you're up for it, please take a look at [this document](https://github.com/neovim/neovim/wiki/FAQ#backtrace-macos--osx).

**Comment by vsandstrom** [comment]
Seems like the issue was with neovim, and is no longer reproducable on the HEAD branch:
```NVIM v0.10.0-dev-1678+g6c14ae6bf-Homebrew```

An issue with ```unpacker.c``` has been fixed in this version, see [https://github.com/neovim/neovim/issues/25184](https://github.com/neovim/neovim/issues/25184)

thanks for all the help @davidgranstrom!
