### ISSUE TITLE
[BUG] Nvim becomes unresponsive due to excessive post window output

### ISSUE THREAD

**Issue by daveriedstra** [davidgranstrom/scnvim#230]
**Describe the bug**
Occasionally SCNvim gets overloaded with `SC_UdpInPort: received error - Bad file descriptor` messages and becomes basically unresponsive. Right now this is happening after an `:SCNvimRecompile` while working with a hardware OSC controller that's continually sending messages. It happens irregularly every 3 or so recompiles. When the controller is powered off, this error does not happen.

The result is that nvim becomes so bogged down that it seems unresponsive. I can still get it to take input (type something, wait a minute or so, and it will happen), but even after quitting SCNvim with `:SCNvimStop` (or killing sclang from outside) the messages continue and nvim remains unresponsive.

![screenshot-2023-11-22_16-11-1700688012](https://github.com/davidgranstrom/scnvim/assets/3504098/57d442ae-2328-4508-8ae6-599721a33bdc)

**Expected behavior**

Not this :)

**Steps to reproduce**

In my case,

1. startup an SCNvim session
2. register OSCDef to controller (along with other things in my project, but this seems most relevant)
4. run `:SCNvimRecompile`
5. messages will sometimes happen at this point; if not, repeat from 2.

**Additional context**

I'm working on an extension to use this particular controller and need to be recompiling while working on the classes.

I wonder if this could be a bug in both supercollider and SCNvim, eg, supercollider is erroring on some UDP function (eg https://github.com/supercollider/supercollider/issues/5337) and neovim tanks because scnvim duly reports the huge volume of error messages. If you think this is more likely to be mainly a supercollider thing, I'm happy to report the bug there.

**Information**

- Operating system

Pop!_OS 22.04

- SuperCollider version

3.11.2

- `nvim --version`

```
NVIM v0.10.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Run "nvim -V1 -v" for more info
```

- Package manager

vim-plug

**Comment by davidgranstrom** [comment]
Hi, thanks for the report. Does this also happen if you recompile using the SuperCollider IDE using the same setup? (If it does it is probably something that needs to be investigated in SuperCollider)

**Comment by davidgranstrom** [comment]
Closing until more info is provided
