### ISSUE TITLE
[BUG] ERROR: Class not defined, ERROR: Could not iterate on directory, 

### ISSUE THREAD

**Issue by jordanwhitede** [davidgranstrom/scnvim#234]
I migrated to lazy.nvim from packer.nvim yesterday, now SCNvim isn't working - I get the following errors on running :SCNvimStart:

ERROR: Class not defined.
  in interpreted text    
  line 1 char 6:         
  SCNvim.port = 48320    

ERROR: Class not defined.                       
  in interpreted text                           
  line 1 char 6:                                
  SCNvim.currentPath = "/home/jordan/test.scd"  

*** ERROR: Could not iterate on directory '/home/jordan/.local/share/SuperCollider/Extensions/scide_scnvim': No such file or directory

**Steps to reproduce**
:SCNvimStart

**Information**

- Operating system
Arch Linux, updated yesterday

- SuperCollider version
3.13.0

- `nvim --version`
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1702233742

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

- Package manager
lazy.nvim

The output of :checkhealth scnvim is:

scnvim
- OK nvim version 0.9.5
- OK sclang executable: /usr/bin/sclang
- OK scnvim classes are installed: /home/jordan/.local/share/SuperCollider/Extensions/
scide_scnvim
- OK keymaps are defined

scnvim documentation
- using HelpBrowser for documentation

scnvim extensions

**Comment by davidgranstrom** [comment]
The symbolic link to `scide_scnvim` did probably change when you changed plugin manager. You should be able manually delete `/home/jordan/.local/share/SuperCollider/Extensions/scide_scnvim` and simply restart `nvim` to re-create the link.

Another solution would be to call: `:lua require('scnvim.install').uninstall()` to delete the invalid symbolic link from within nvim (but you will achieve the same effect by manually deleting it)

**Comment by jordanwhitede** [comment]
This worked instantly, thankyou.
