### ISSUE TITLE
[BUG] UGen Arguments not visible

### ISSUE THREAD

**Issue by jordanwhitede** [davidgranstrom/scnvim#236]
![scnvim](https://github.com/davidgranstrom/scnvim/assets/65348852/f0a4ab69-6df1-4d79-8437-e25d1018f398)
The arguments of UGens aren't showing up. I'm using nvim-cmp for completion and ran :SCNvimGenerateAssets, autocompletion works fine but the UGen arguments aren't visible (see screenshot).

- Operating system
Arch Linux

- SuperCollider version
3.13.0

- `nvim --version`
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1702233742

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

- Package manager
lazy.nvim

**Comment by davidgranstrom** [comment]
Could it be an issue with the colorscheme that makes the text (i.e. arguments) appear invisible?

**Comment by jordanwhitede** [comment]
Ahhh, that's embarrassing, yes it was an issue with my nvim-cmp color scheme, sorry.
