### ISSUE TITLE
[BUG] C-e for sending block only sends the current line

### ISSUE THREAD

**Issue by lex6i** [davidgranstrom/scnvim#249]
**Describe the bug**
When using ctrl - e only the current line is evaluated,  even though supercollider syntax is correct, and encapsulated in parentheses.  I'm on a fresh install of Arch with minimal other plugins aside from Coc.

**Expected behavior**
The whole block would be sent

**Information**

- Operating system
Fresh up to date Arch

- SuperCollider version
3.13

- `nvim --version`
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1720049189

- Package manager
Lazy

**Comment by davidgranstrom** [comment]
Thanks for the report. Could you please provide a (SuperCollider) code sample of the issue you are describing? I just opened a PR for a somewhat related bug, perhaps this solves your issue too?
