### ISSUE TITLE
The post window has no memory

### ISSUE THREAD

**Issue by danielmkarlsson** [davidgranstrom/scnvim#25]
The post window does not "remember" what size it was when toggled back and forth with Enter.

I expected to be able to resize the post window, then toggle it off and on again retaining the resizing I had done.

Resize post window, toggle to off, toggle to on.

I think that this might be a useful feature as we are progressing more and more into look and feel of our environments being the equivalent to pyrotechnics at an AC/DC show, however subtle and understated, the devil is ever-present in the details.

NVIM v0.3.1
Mac OS 10.13.6
Running scnvim in Kitty version 0.12.3

**Comment by davidgranstrom** [comment]
Yes, I agree that this would be nice to have. I will look into this, in the meantime you can tweak the absolute size of the post window using the `scnvim_postwin_size` setting, e.g:

```vim
let g:scnvim_postwin_size = 45
```
