### ISSUE TITLE
[BUG] .loadRelative error

### ISSUE THREAD

**Issue by gilfuser** [davidgranstrom/scnvim#28]
**Describe the bug**
Evaluating `"FX/fxLib.scd".loadRelative` will show this error:
```
ERROR: can't load relative to an unsaved file
CALL STACK:
	Exception:reportError
		arg this = <instance of Error>
	Nil:handleError
		arg this = nil
		arg error = <instance of Error>
	Thread:handleError
		arg this = <instance of Thread>
		arg error = <instance of Error>
	Object:throw
		arg this = <instance of Error>
	String:loadRelative
		arg this = "FX/fxLib.scd"
		arg warn = true
		arg action = nil
		var path = nil
	Interpreter:interpretPrintCmdLine
		arg this = <instance of Interpreter>
		var res = nil
		var func = <instance of Function>
		var code = "	"FX/fxLib.scd".loadRelative;"
		var doc = nil
		var ideClass = nil
	Process:interpretPrintCmdLine
		arg this = <instance of Main>
^^ The preceding error dump is for ERROR: can't load relative to an unsaved file
```
The file is saved, btw.

**Expected behavior**
Load other .scd files through relative paths

**Steps to reproduce**
Having two .scd files in a folder, say patch1.scd and patch2.scd, evaluate `"patch2.scd".loadRelative` in patch1.scd

**Information**
- `nvim --version`: 0.3.1
- Operating system: Linux Ubuntu Studio 18.10
- Running scnvim in a Terminal/GUI: terminator

**Comment by madskjeldgaard** [comment]
hi @gilfuser . I don't think `.loadRelative` works outside of the IDE unfortunately, the same goes with the Document class. .loadRelative relies on the result of `thisProcess.nowExecutingPath` which returns nil outside of the IDE.

**Comment by gilfuser** [comment]
Hi @madskjeldgaard 
I see. Now I remember I had a similar conversation in the SCVim github.
Well, with some minor changes in my code I can use `(someFile.scd).load` instead, so it's all right.

thanks

best regards

**Comment by gilfuser** [comment]
Actually `.asRelativePath.load` does the same as `.loadRelative` and works with SCNvim, and if I'm right the only difference being it's not possible to use wildcards.
