### ISSUE TITLE
SCDoc integration

### ISSUE THREAD

**Issue by davidgranstrom** [davidgranstrom/scnvim#3]
Be able to browse SuperCollider documentation directly in vim. The native HelpBrowser uses javascript for Search and for methods (as they can be implemented by many classes). The methods could be filtered on the vim side and displayed in the quickfix window instead.

- [x] ~~Finish [SCDocVimRenderer](https://github.com/davidgranstrom/SCDocVimRenderer)~~
    - [x] Make sure renderer doesn't conflict with HelpBrowser/IDE
    - [x] Export docmap as valid json
- [x] Emulate search/methods and display results in the quickfix window
    - [x] Methods
    ~- [ ] Search by query~
    - [x] Check that file exists before jump
    - [x] Apply conceal for file paths in quickfix list
- [x] Be able to open rendered help files in vim
- [x] Reuse same window for help

**Comment by davidgranstrom** [comment]
`SCDocVimRenderer` has been replaced by `SCNvimDocRenderer` in PR #6 which uses `pandoc` to render html files with some additional vim help markup on-the-fly. Note that there will be a dependency on `pandoc` to use this feature.

**Comment by kflak** [comment]
Hey there, 

I obviously got very excited when I heard rumors of this finally working, but for some reason it's not happening on my system. Shift-K does what it usually does, which is to open the old help browser. I tried to do a clean reinstall of scnvim, as well as adding ``let g:scnvim_scdoc = 1`` to my init.vim. Arch linux, as always, pandoc location ``/usr/bin/pandoc``, pandoc v 2.7.3. I'd be happy to go bug-hunting, but don't really know where to start...

**Comment by davidgranstrom** [comment]
Hi @kflak!

Could you post the output of "scnvim" section after running `:checkhealth` in nvim, just so we know for sure that scnvim finds your pandoc executable?

Also, make sure that you have done `:UpdateRemotePlugins` after the scnvim update since the python part of the plugin has been updated.

The third thing that comes to mind is to check that you have properly installed the SCNvim.sc classes so that SuperCollider can find them (since there are some new additions to make SCDoc integration work). My suggestion is to create a symlink from the `sc` directory of this plugin like so: 
```
ln -s <PATH_TO_SCNVIM_PLUGIN>/sc ~/Library/Application\ Support/SuperCollider/Extensions/scide_scvim
```
(and adjust the path according to the location of your Extenions directory). You could also create a `scide_scvim` directory in your Extensions dir, and just symlink the `sc` dir to the `scide_scvim` dir.

I'm hoping to automate this part of the plugin installation in the future..

**Comment by kflak** [comment]
Thanks for the quick answer!

Here is the output of :checkhealth
```
health#scnvim#check
========================================================================
## scnvim
  - OK: has("timers") - success
  - INFO: sclang executable: /usr/bin/sclang
  - INFO: has("python3") - success

health#scnvim#check
========================================================================
## scnvim
  - OK: has("timers") - success
  - INFO: sclang executable: /usr/bin/sclang
  - INFO: has("python3") - success

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $VTE_VERSION='5602'
  - INFO: $COLORTERM='truecolor'

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: wl-copy

## Python 2 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          /usr/bin/python2 does not have the "neovim" module. :help |provider-python|
          /usr/bin/python2.7 does not have the "neovim" module. :help |provider-python|
          python2.6 not found in search path or not executable.
          /usr/bin/python is Python 3.7 and cannot provide Python 2.
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/bin/python3
  - INFO: Python version: 3.7.3
  - INFO: pynvim version: 0.3.2
  - OK: Latest pynvim is installed.

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help |g:ruby_host_prog| for non-standard gem installations.

## Node.js provider (optional)
  - INFO: Node.js: v11.15.0
  - WARNING: Missing "neovim" npm (or yarn) package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Run in shell (if you use yarn): yarn global add neovim

```
I suppose the lack of python 2 is not a problem? Arch defaults to python 3, I'm not sure if this is relevant. 

I have symlinked as suggested, but so far no luck in changing the help browser behavior.

**Comment by davidgranstrom** [comment]
@kflak Thanks for the info! It looks a bit strange that you have two sections of "scnvim", both missing the "pandoc executable" test. Here is the output of `:checkhealth` on my machine as a comparison:
```
health#scnvim#check
========================================================================
## scnvim
  - OK: has("timers") - success
  - INFO: using g:scnvim_sclang_executable = ~/bin/sclang
  - INFO: sclang executable: /Users/<USER>/bin/sclang
  - INFO: pandoc executable: /usr/local/bin/pandoc
  - INFO: has("python3") - success
```

Do you use a plugin manager (such as vim-plug) to manage your nvim plugins? I would suggest to reinstall the plugin, and make sure that you only have one copy of it as well (just a hunch because of the double scnvim output from your checkhealth). Then run `:checkhealth` again to confirm that you have the "pandoc executable" line. (you could also take a look inside `autoload/health/scnvim.vim` to make sure that the pandoc check exists in your local copy.

**Comment by kflak** [comment]
Ah, that's where doggy's buried... I recently migrated from minpac to vim-plug, and forgot to clean out the cruft. Now pandoc shows up in ``:checkhealth``, and sc help browser is no longer showing up. However, I am getting this when shift-K-ing: 
```
ERROR: Class not defined.
  in interpreted text
  line 1 char 6:
  SCNvim.openHelpFor("Pbind", 9670, "", "/usr/bin/pandoc"); 
        
```

I tried running SCnvimTags, but it doesn't seem to do the trick.

**Comment by davidgranstrom** [comment]
@kflak Okay, make sure that you have the correct symlink from the `sc` directory (from the "minpac" installation). That class extension should be located in `sc/SCNvimDoc/extSCNvim.sc` so it should be defined if your symlink is setup correctly.

**Comment by kflak** [comment]
Hmmm... still having trouble getting the symlinking to work. However, if I include the plugin dir in my compile paths, it works without issue! Very exciting...

**Comment by kflak** [comment]
sclang_conf.yaml, that is...
