### ISSUE TITLE
[BUG] Help system crashing SC

### ISSUE THREAD

**Issue by madskjeldgaard** [davidgranstrom/scnvim#30]
**Describe the bug**
Recently, I started getting this strange bug. When I look up something in the help system once, it works fine. 

If I keep the help window open and look up a second class, SuperCollider crashes. 
If I on the other hand close the help window before looking up a second class, SuperCollider is fine. 

In the SCIDE everything seems fine.

**Expected behavior**
To not crash SC when looking up a second class. 

**Steps to reproduce**
Open NVIM and SCNvim with a scd file. 
Write a class name (SinOsc for example)
Look it up (using shift-K) in the help system
Do not close the help file window but keep it open.
Return to NVIM and look up another class. 
Boom: Crash. 

**Additional context**
This is the errors in the post window in SCNvim (but I think they're the usual ones caused by half broken help system in SC?):
```
QObject::connect: No such slot QtCollider::WebView::onRenderProcessTerminated(RenderProcessTerminationStatus, int)
JavaScript Message: WebSocket connection to 'ws://localhost:12344/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
JavaScript Message: WebChannel error: [object Event]
QObject::connect: No such slot QtCollider::WebView::onRenderProcessTerminated(RenderProcessTerminationStatus, int)
JavaScript Message: WebSocket connection to 'ws://localhost:12344/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
JavaScript Message: WebChannel error: [object Event]
QObject::connect: No such slot QtCollider::WebView::onRenderProcessTerminated(RenderProcessTerminationStatus, int)
JavaScript Message: WebSocket connection to 'ws://localhost:12344/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
JavaScript Message: WebChannel error: [object Event]
QObject::connect: No such slot QtCollider::WebView::onRenderProcessTerminated(RenderProcessTerminationStatus, int)
JavaScript Message: WebSocket connection to 'ws://localhost:12344/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
JavaScript Message: WebChannel error: [object Event]
```

**Information**
- `nvim --version`: NVIM v0.3.4
- Operating system: MacOS 10.14.4
- Running scnvim in a Terminal/GUI: Kitty

**Comment by davidgranstrom** [comment]
Yes, I can confirm that this is happening here as well. What version of SuperCollider are you running?
I get the feeling that this started to happen after I updated SuperCollider so it would be good to compare versions and find the change which causes this behaviour.

In the mean time, you might want to check out PR #6 which uses vim splits to display documentation in a plain text format. If you decide to try it out, I would be happy for any feedback or comments that you might have!

**Comment by madskjeldgaard** [comment]
I forgot to mention the SC version, sorry! 3.10.2. I get the feeling that it happened with this version as well. But it's strange that SCIDE seems unaffected.

**Comment by davidgranstrom** [comment]
I haven't looked closely at this yet, but I think that ScIDE uses a different type of window/docklet for rendering the documentation, whereas the HelpBrowser (without IDE) opens up a new `Window` and uses different code paths.

**Comment by madskjeldgaard** [comment]
Okay this is definately an SC problem. 
I tried downgrading to 3.10.1 which still had the same problem.
Then tried 3.10.0 which works normally. So something happened after 3.10.0. I'll let the devs know about this.

**Comment by madskjeldgaard** [comment]
This is now a SuperCollider issue:[https://github.com/supercollider/supercollider/issues/4403]( https://github.com/supercollider/supercollider/issues/4403)

**Comment by davidgranstrom** [comment]
@madskjeldgaard I'll close this issue for now. I just merged the SCDoc support PR for scnvim, so that might be an option until [#4403](https://github.com/supercollider/supercollider/pull/4267) is merged. There is a new section about the SCDoc integration in `:h SCNvim` and some updates to the README as well.
