### ISSUE TITLE
Add a FAQ section in the docs

### ISSUE THREAD

**Issue by davidgranstrom** [davidgranstrom/scnvim#31]
Like the title says. We could collect various tips and tricks for scnvim which otherwise would be lost (or at least harder to find) on the issue tracker.

**Comment by madskjeldgaard** [comment]
This is a great idea. I have some stuff to contribute. 

Should the section maybe rather be named "Tips and tricks" and added before the Thanks section of the README?

Not sure what's meant by "collecting in the issue tracker" ? Is that here?

**Comment by davidgranstrom** [comment]
@madskjeldgaard Okay, great to hear!

I think we should add this to the native documentation i.e. https://github.com/davidgranstrom/scnvim/blob/master/doc/SCNvim.txt maybe after section 5 (configuration)? We might also mirror some of the stuff in the README, but it is already quite lengthy I think. Maybe we should create a (github) wiki at some point and move some stuff over to that. 

Yup, I meant this issue tracker. Sometimes questions pop up (like you had yesterday about configuring the post window), I think some of that stuff could definitely belong in the "Tips and tricks"/"FAQ" section so it's easy for users to discover.

**Comment by madskjeldgaard** [comment]
Okay sounds great. So then maybe it's a good idea to add tips to this issue and then at some point compile them to the help file in NVIM

**Comment by davidgranstrom** [comment]
Yes, that would be a good start!

**Comment by madskjeldgaard** [comment]
**Make the post window text wrap**
`autocmd FileType scnvim setlocal wrap`

**Map any piece of SuperCollider code to a key**
`au filetype supercollider nnoremap <f2> :call scnvim#sclang#send('"helloworld".postln')<CR>`

**Map any piece of SuperCollider code to a key (silent version)**
`au filetype supercollider nnoremap <f3> :call scnvim#sclang#send_silent('"[quietly whispering]: Hello World!".postln')<CR>`

**Comment by kflak** [comment]
**Map the space bar to evaluate code**
```
autocmd FileType supercollider nmap <Space> <Plug>(scnvim-send-block)
```

**Comment by davidgranstrom** [comment]
Added these tips to the new [wiki](https://github.com/davidgranstrom/scnvim/wiki), thanks a lot! (Also, please add more content to the wiki if you have more ideas!)
