### ISSUE TITLE
[BUG] Post window buffer gets screwed up with Sessions.vim

### ISSUE THREAD

**Issue by madskjeldgaard** [davidgranstrom/scnvim#33]
**Describe the bug**
When using SCNvim with[ Sessions.vim](http://peterodding.com/code/vim/session/), post windows can end up piling up and causing everything to be a bit screwed up when reopening a previous session.

<img width="1440" alt="Skærmbillede 2019-07-01 kl  16 00 43" src="https://user-images.githubusercontent.com/22474608/60442697-e022c000-9c19-11e9-9860-5be182c65174.png">

**Expected behavior**
That SCNvim would recognise that a post window buffer is already open on session load and act accordingly (ie not make a new one if one exists).

**Steps to reproduce**
Open NeoVim with a SuperCollider buffer, start SCNVim. 
Keep the post window buffer open
run `:SaveSession sc` to save the session
`:wqa` 
and then reopen vim and run  `:OpenSession sc` to reopen the saved session. 
Now, run `:SCNvimStart`

**Additional context**
Tested within Tmux

**Information**
- `nvim --version`: 0.3.5
- Operating system: MacOS 10.14.4 (18E226)
- Running scnvim in a Terminal/GUI: Kitty

**Comment by davidgranstrom** [comment]
@madskjeldgaard Thanks for the report. I can confirm that this happens with `:mksession` as well. I have fix that I will try out and then get back to you.

**Comment by davidgranstrom** [comment]
@madskjeldgaard I think I have a fix for saving/loading sessions with scnvim now. The fix is in this [PR](https://github.com/davidgranstrom/scnvim/pull/34)  if you would like to try it out. Here's how you can switch to the branch (if you are using vim-plug)
```
Plug 'davidgranstrom/scnvim', { 'branch': 'topic/support-sessions' }
```

**Comment by madskjeldgaard** [comment]
Yes! This works!

**Comment by davidgranstrom** [comment]
@madskjeldgaard great to hear! I've merged this to master now.

**Comment by madskjeldgaard** [comment]
yehaaaaaa
