### ISSUE TITLE
[BUG] SCNVim under Windows Subsystem for Linux (WSL) Ubuntu

### ISSUE THREAD

**Issue by madskjeldgaard** [davidgranstrom/scnvim#36]
**Describe the bug**
This is perhaps not a bug, perhaps it is. I am trying to set up SCNvim to work under WSL in Windows, specifically in Ubuntu. Most of it seems to work at the moment. NeoVim seems healthy, I can open the post window and use sclang. But there is a number of problems listed below. These are probably more related to WSL and SC but I'll post them here in case it's fixable in SCNVIM. 

my .zshrc file has aliases for scsynth and sclang that look like the following
```alias sclang="/mnt/c/Program\ Files/SuperCollider-3.10.2/sclang.exe"  
alias scsynth="/mnt/c/Program\ Files/SuperCollider-3.10.2/scsynth.exe"  
```
Both seem to work when tested on the command line.

But then a number of smaller but quite esoteric errors happen when using it all in scnvim...

**Errors**

When opening up a .scd file the following error occurs:
`[scnvim]: json decode error: Expecting value: line 1 column 1 (char 0)%`

When trying to boot the server:
`'scsynth.exe' is not recognized as an internal or external command, operable program or batch file.`

When starting SCNvim the post window says this before compiling:
`ERROR: Cannot change to runtime directory: No such file or directory`

I hope someone here can help me out of this misery. Thanks!

**Comment by madskjeldgaard** [comment]
okay, the server is now booting. this was because of some weird platform stuff in sc (https://github.com/supercollider/supercollider/issues/2719), but the remaining issues are still there it seems. Here is the error I get when trying to generate tag files:

```
ERROR: Primitive '_FileWrite' failed.
Failed.
RECEIVER:
Instance of File {    (0000024A0933E2B8, gc=C4, fmt=00, flg=00, set=02)
  instance variables [1]
    fileptr : nil
}
CALL STACK:
	MethodError:reportError
		arg this = <instance of PrimitiveFailedError>
	Nil:handleError
		arg this = nil
		arg error = <instance of PrimitiveFailedError>
	Thread:handleError
		arg this = <instance of Thread>
		arg error = <instance of PrimitiveFailedError>
	Thread:handleError
		arg this = <instance of Routine>
		arg error = <instance of PrimitiveFailedError>
	Object:throw
		arg this = <instance of PrimitiveFailedError>
	Object:primitiveFailed
		arg this = <instance of File>
	Meta_SCNvim:generateTags
		arg this = <instance of Meta_SCNvim>
		arg outputPath = "/home/madskjeldgaard/dotfile..."
		var tagPath = "/home/madskjeldgaard/dotfile..."
		var tagFile = <instance of File>
		var tags = [*0]
	< FunctionDef in Method Meta_SCNvim:generateAssets >  (no arguments or variables)
	Routine:prStart
		arg this = <instance of Routine>
		arg inval = 192.9024438
^^ The preceding error dump is for ERROR: Primitive '_FileWrite' failed.
Failed.
RECEIVER: a File

```

**Comment by madskjeldgaard** [comment]
> 
> 
> okay, the server is now booting. this was because of some weird platform stuff in sc ([supercollider/supercollider#2719](https://github.com/supercollider/supercollider/issues/2719)), but the remaining issues are still there it seems. Here is the error I get when trying to generate tag files:
> 
> ```
> ERROR: Primitive '_FileWrite' failed.
> Failed.
> RECEIVER:
> Instance of File {    (0000024A0933E2B8, gc=C4, fmt=00, flg=00, set=02)
>   instance variables [1]
>     fileptr : nil
> }
> CALL STACK:
> 	MethodError:reportError
> 		arg this = <instance of PrimitiveFailedError>
> 	Nil:handleError
> 		arg this = nil
> 		arg error = <instance of PrimitiveFailedError>
> 	Thread:handleError
> 		arg this = <instance of Thread>
> 		arg error = <instance of PrimitiveFailedError>
> 	Thread:handleError
> 		arg this = <instance of Routine>
> 		arg error = <instance of PrimitiveFailedError>
> 	Object:throw
> 		arg this = <instance of PrimitiveFailedError>
> 	Object:primitiveFailed
> 		arg this = <instance of File>
> 	Meta_SCNvim:generateTags
> 		arg this = <instance of Meta_SCNvim>
> 		arg outputPath = "/home/madskjeldgaard/dotfile..."
> 		var tagPath = "/home/madskjeldgaard/dotfile..."
> 		var tagFile = <instance of File>
> 		var tags = [*0]
> 	< FunctionDef in Method Meta_SCNvim:generateAssets >  (no arguments or variables)
> 	Routine:prStart
> 		arg this = <instance of Routine>
> 		arg inval = 192.9024438
> ^^ The preceding error dump is for ERROR: Primitive '_FileWrite' failed.
> Failed.
> RECEIVER: a File
> ```

I guess this is caused by vim being in the ubuntu subsystem's filesystem and sc in the windows subsystem

**Comment by davidgranstrom** [comment]
Hey @madskjeldgaard, thanks for the report!

Could you try this from WSL and see if it produces a tag file in your home dir? 
```supercollider
SCNvim.generateTags("~/scnvim_tags");
```

**Comment by madskjeldgaard** [comment]
It produced the tags file in the windows part of my file system c:\Users\Mads Kjeldgaard/scnvim_tags

So I guess I just need vim to read that tags file. Is there a variable I can set to this path and have that read the tag file ? If so, I guess this is it!

PS. I'll gather my experiences with this in a tip of sorts for the readme, when I'm done. There's a few tricky bits to it.

**Comment by madskjeldgaard** [comment]
I can get hold of the tag file from within WSL using `/mnt/c/Users/Mads\ Kjeldgaard/scnvim_tags`

**Comment by davidgranstrom** [comment]
Okay, interesting. Yes, you should be able to use that file by setting `:set tags+= /mnt/c/Users/Mads\ Kjeldgaard/scnvim_tags`. 

This is the relevant SCNvim.sc function:
```
    *generateAssets {|rootDir|
        var tagsPath = rootDir +/+ "scnvim-data/tags";
        var syntaxPath = rootDir +/+ "syntax/classes.vim";
        var snippetPath = rootDir +/+ "scnvim-data/supercollider.snippets";
        Routine.run {
            SCNvim.generateTags(tagsPath);
            SCNvim.generateSyntax(syntaxPath);
            SCNvim.generateSnippets(snippetPath);
        };
    }
```
It passes in the value of `scnvim_root_dir` which is set to the scnvim plugin install dir at startup. You could try and set the value of `scnvim_root_dir` to a path on your windows system which contains two directories like this: `C:\scnvim_assets\{scnvim-data,syntax}`. And then set `:let scnvim_root_dir = C:\scnvim_assets` and run `:SCNvimTags` and see if that works. You could then manually move these files to the scnvim install dir until we find a more elegant solution.

**Comment by ranjithshegde** [comment]
@davidgranstrom 

Is there a way to set the path to scsynth the same way you can point to sclang?

A little bit of context - I am using SCNvim from windows. (basic windows no WSL) and following normal installation,  nvim checkhealth asked me to set scnvim-sclang_executable to the right directory which I did and scnvim launches fine. but the server can be booted only if I launch scnvim from the dir containing scsynth.

I will move this to a separate issue if is required

**Comment by davidgranstrom** [comment]
@ranjithshegde Thanks for the report. Windows is a very untested platform at the moment unfortunately, so I'm very grateful for any bug reports.

The server program should already be set by SuperCollider itself, so I don't think we need to introduce a setting in scnvim for this.

This is how it is set in `WindowsPlatform.sc`
```supercollider
Server.program = "scsynth.exe";
```

I'm guessing you would need to specify an absolute path instead since we're not launching sclang from the IDE.

This might do the trick? From this [issue](https://github.com/supercollider/supercollider/issues/2719#issuecomment-462904547)

```supercollider
Server.program = Platform.resourceDir +/+ "scsynth.exe"
```

If that works, you could add that line to your `startup.scd` and guard it like this so it won't affect the IDE.

```supercollider
if (\SCNvim.asClass.notNil) {
    Server.program = Platform.resourceDir +/+ "scsynth.exe";
}
```

Let me know if it's working, we could maybe inject this at scnvim startup explicitly for Windows if that's the case.

**Comment by ranjithshegde** [comment]
@davidgranstrom 

Thank you for your response. I will absolutely take it upon myself to find and report bugs. I will use SC in windows for the next few weeks so that I can run my usual patches and eventually encounter problems!

`if (\SCNvim.asClass.notNil) {
    Server.program = Platform.resourceDir +/+ "scsynth.exe";
}`
As suggested by you, I put that in my startup file and voila, it looks for the right file. However, I had to go back to the issue you referred to because I encountered another problem. SCsynth in windows is usually in `C:\Program Files`, which has  a space , confuses the shell. I had to insert a .quote like this

`if (\SCNvim.asClass.notNil) {
    Server.program = (Platform.resourceDir +/+ "scsynth.exe").quote;
}`

There is also an error with SCNvimTags. I will go through the solutions above. If it does not fix it, I will put all this and the error in a separate issue tomorrow

**Comment by madskjeldgaard** [comment]
Hi! 

I am closing this now as it seems to not be an issue with latest SCNvim under WSL version 2. The current status for scnvim/supercollider on WSL is that it works fine, except for sound. I don't think WSL supports using alsa/jack but I might be wrong. One could probably launch a server on the main windows system and control it from scnvim within wsl2 but haven't tried that yet.

Help system and all other non sound producing features in scnvim works as expected. 

Tip for anyone else: You need to compile and install supercollider gui-less on your WSL system (I used Debian) like this: https://github.com/supercollider/supercollider/blob/develop/README_RASPBERRY_PI.md

I might get back to trying to find a good workflow for communication between scnvim in wsl2 and the main windows system at some point but that's not relevant to this issue right now.

best

**Comment by bagong** [comment]
You might want to give this some time, WSL is still in flow, and it looks like they'll want to support audio fully midterm too...
