### ISSUE TITLE
[BUG] Rendering Help with Pandoc Doesn't Work on Windows

### ISSUE THREAD

**Issue by thereblight** [davidgranstrom/scnvim#37]
**Describe the bug**

On Windows, SCNvim Help does not work with 'g:scnvim_scdoc = 1'.

**Expected behavior**

When I put cursor on an object or method and press shift k, a help window or a quickfix window should open.

**Steps to reproduce**

When I put cursor on an object or method and press shift k, nothing happens and these error messages appear on the sclang console and nvim

> 'C:Program' is not recognized as an internal or external command, operable program or batch file.

> [scnvim]: json decode error: Invalid \escape: line 1 column 29 (char 28)

**Additional context**

Actually I tried to apply some dirty fixes myself and got it working on my machine (only). FYI, I will describe here what I remember I've done. Hope this helps.

- backslash escape related

First, I installed pandoc on another location with no space character in the path name, and set pandoc executable variable, with 4 backslashes each instead of one.

`let g:scnvim_pandoc_executable = "C:\\\\ProgramData\\\\chocolatey\\\\bin\\\\pandoc"`

(With spaces in the path like "Program Files", I couldn't find a way to successfully run pandoc from supercollider with .unixCmd.)

After that, in sc/Classes/SCNvimDoc/extSCNvim.sc from line 41 (openHelpFor method), I added .replace("\\\\", "\\\\\\\\") to the path strings.

>            msg = "{\"action\":{\"help\":{\"uri\":\"%\",\"pattern\":\"%\"}}}".format(outputPath.replace("\\", "\\\\"), pattern); //my fix
>        } {
>            // search for method
>            msg = "{\"action\":{\"help\":{\"method\":\"%\",\"helpTargetDir\":\"%\"}}}".format(uri.asString, SCDoc.helpTargetDir.replace("\\", "\\\\")); //my fix`

- character encoding related

Now shift-k invoked a new error message regarding parsing docmap and cp949. I put an encoding option in /rplugin/python3/scnvim/help.py line 27.

>                with open(os.path.join(path, 'docmap.json'), encoding='utf-8') as file:

- EOL related

From Here shift - k on class name started to work, but when I close the help window and shift - k on it again I got a bunch of error messages. It said something about ^M, so I guessed something couldn't understand WIndows EOL. I appended pandoc EOL option in sc/Classes/SCNvimDoc/extSCNvim.sc line 40 and the error was gone.

>             "% \"%\" --from html --to plain -o \"%\" --eol=lf".format(pandocPath, path, outputPath).unixCmdGetStdOut;

- backslash escape related again

Lastly, shift -k on a method opened a quickfix window, but from there I couldn't open a help window, with json decode error. The problem was that uri string that goes into SCNvim.renderMethod  lost all of its backlashes, and I succeeded to put them back by manipulating a:uri in autoload/scnvim/help.vim, from line 60.

>`  let uri_winfix = substitute(a:uri, "\\", "\\\\\\\\", "g") " my fix`
>`  if has_pandoc`
>`    let cmd = printf("SCNvim.renderMethod(\"%s\", %d, \"%s\", \"%s\")",`
>`          \ uri_winfix, g:scnvim_python_port, a:pattern, pandoc_path) " my fix`

**Information**
- `nvim --version`: 0.3.8
- Operating system: Windows 10
- Running scnvim in a Terminal/GUI: GUI

**Comment by davidgranstrom** [comment]
@thereblight Thank you for your report! This plugin has not received much testing on Windows (yet), so this is greatly appreciated. 👍 

It sounds like you found ways around all issues, would you consider submitting a PR with your mentioned fixes?

**Comment by thereblight** [comment]
That's great. I'm not really a developer and I don't know how use git and what exactly PR is, but I'll try when I have some free time. I got a quite helping friend called google.

At the same time, (I think you already know it but) consider that this is not really a fix, and it's highly possible that this will break the pandoc help system on other OSes.

**Comment by davidgranstrom** [comment]
@thereblight No worries! I'll test your fixes when I get my hands on a Windows machine, possibly later this week.

**Comment by ranjithshegde** [comment]
@thereblight 

If you put your path in ().quote, it solves the problem of space such as in 'Program Files(x86)'

Glad to know you are using it on windows as well. I have encountered a few problems myself. Will make a bug report if I cant find workarounds after a while

**Comment by davidgranstrom** [comment]
This should now be working since #97 was merged. There is also some other small improvements for Windows that has been merged recently. I've tested using `pandoc` installed via the `chocolatey` package manager.
