### ISSUE TITLE
[BUG] ScnVimHelp doesn't recognize methods

### ISSUE THREAD

**Issue by kflak** [davidgranstrom/scnvim#38]
The help function works beautifully on Classes, but not .methods...When I do shift-K on any method I get this:
[scnvim]: error parsing docmap Invalid \escape: line 353 column 36 (char 18442)

**Comment by davidgranstrom** [comment]
@kflak Thanks for the report. Can you confirm that `docmap.json` exists in  the `SCDoc.helpTargetDir` directory, and possibly run that file through a JSON linter to see that it validates correctly?

**Comment by kflak** [comment]
Hi,

docmap.json exists in the ~/.local/share/SuperCollider/Help dir. Ran it through JSONLint (there's a first time for everything), and I got the following error:
Error: Parse error on line 353:
...Spec",		"summary": "datatype specifiyin
----------------------^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'undiefined'

**Comment by davidgranstrom** [comment]
Okay, thanks. So there seems to be something wrong with the docmap creation.. I cannot reproduce it locally though. Could you post the surrounding context of line 535 maybe +10 lines above/below or so. Also, try and delete `docmap.json` and re-create it by pressing `K` on a method name and see if the same error is reproduced.

**Comment by kflak** [comment]
Here it is: 
```
"Classes/QuadN": {
"title": "QuadN",
"path": "Classes/QuadN",
"summary": "General quadratic map chaotic generator",
"installed": "standard",
"categories": "UGens>Generators>Chaotic",
"keywords": [  ],
"related": [ "Classes/QuadL","Classes/QuadC" ],
"methods": [ "*ar","?*equation" ],
"superclasses": [ "ChaosGen","UGen","AbstractFunction","Object" ],
"subclasses": [ "QuadL","QuadC" ]
},
"Classes/ScalarSpec": {
"title": "ScalarSpec",
"path": "Classes/ScalarSpec",
"summary": "datatype specifiying a \scalar \"rate\" input or output",
"installed": "extension",
"categories": "Spec, Libraries>crucial>Spec",
"keywords": [  ],
"related": [  ],
"methods": [ "-canKr","-rate","*newFrom" ],
"superclasses": [ "ControlSpec","Spec","Object" ]
},
"Classes/Drand": {
"title": "Drand",
"path": "Classes/Drand",
"summary": "Demand rate random sequence generator.",
"installed": "standard",
"categories": "UGens>Demand",
"keywords": [  ],
"related": [ "Classes/Demand","Classes/Dseq","Classes/Dser","Classes/Duty","Classes/Dxrand","Classes/TDuty" ],
"methods": [ "*new" ],
"superclasses": [ "ListDUGen","DUGen","UGen","AbstractFunction","Object" ]
```
And I tried recreating the file, same result as before.

**Comment by davidgranstrom** [comment]
@kflak thanks. i think that the problem is the `\` in the summary of ScalarSpec. Could you check out this branch and see if it fixes it?
```
Plug 'davidgranstrom/scnvim', {'branch': 'topic/escape-backslash'}
```

**Comment by kflak** [comment]
Done. Now I'm getting 
```
error parsing docmap Expecting ',' delimiter: line 353 column 48 (char 18454)
```
after a clean reinstall and trashing of docmap.json

**Comment by davidgranstrom** [comment]
@kflak Okay, does the docmap pass the linter now? Also, please post the surrounding context of line 353 from docmap.json so I can investigate.

**Comment by kflak** [comment]
```
Error: Parse error on line 353:
...ng a \\scalar \\"		rate\\ " input or ou
----------------------^
Expecting 'EOF', '}', ':', ',', ']', got 'undefined'
```

and the context:
```
"subclasses": [ "QuadL","QuadC" ]
},
"Classes/ScalarSpec": {
"title": "ScalarSpec",
"path": "Classes/ScalarSpec",
"summary": "datatype specifiying a \\scalar \\"rate\\" input or output",
"installed": "extension",
"categories": "Spec, Libraries>crucial>Spec",
"keywords": [  ],
"related": [  ],
"methods": [ "-canKr","-rate","*newFrom" ],
"superclasses": [ "ControlSpec","Spec","Object" ]
},
"Classes/Drand": {
"title": "Drand",
"path": "Classes/Drand",
"summary": "Demand rate random sequence generator.",
"installed": "standard",
"categories": "UGens>Demand",
"keywords": [  ],
"related": [ "Classes/Demand","Classes/Dseq","Classes/Dser","Classes/Duty","Classes/Dxrand","Classes/TDuty" ],
"methods": [ "*new" ],
"superclasses": [ "ListDUGen","DUGen","UGen","AbstractFunction","Object" ]
},
```

**Comment by davidgranstrom** [comment]
Thanks! I just pushed a fix to the same branch, please try it out when you have the time.

**Comment by kflak** [comment]
That seems to do the trick! Nice solution, by the way...

**Comment by davidgranstrom** [comment]
@kflak Great! I'll merge #40 then.

**Comment by kflak** [comment]
Excellent! Updated to #40 and everything seems to work well.
