### ISSUE TITLE
Security hole / passing command line flags to scsynth

### ISSUE THREAD

**Issue by kflak** [davidgranstrom/scnvim#39]
Is there a way to pass command line options to scsynth fron scnvim? Referring to [this](https://github.com/supercollider/supercollider/issues/4496) security hole, it seems like it would be nice to be able to simply pass the correct flag on scnvimstart?

**Comment by davidgranstrom** [comment]
SCNvim does not explicitly launch `scsynth` so the fix suggested in https://github.com/supercollider/supercollider/issues/4496 applies for SCNvim as well.
