### ISSUE TITLE
[BUG] help.supercollider doesn't respect init.vim keyboard reassignments

### ISSUE THREAD

**Issue by kflak** [davidgranstrom/scnvim#41]
**Describe the bug**

I have this in my init.vim:
```
inoremap <C-J> <C-W><C-J>
inoremap <C-K> <C-W><C-K>
inoremap <C-L> <C-W><C-L>
inoremap <C-H> <C-W><C-H> 
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>
```
But whenever I navigate to a help window I need to fall back to good old C-W C-{j,k,l,h}. Putting this into an aucmd group fixes it:
```
    autocmd FileType help.supercollider inoremap <C-J> <C-W><C-J>
    autocmd FileType help.supercollider inoremap <C-K> <C-W><C-K>
    autocmd FileType help.supercollider inoremap <C-L> <C-W><C-L>
    autocmd FileType help.supercollider inoremap <C-H> <C-W><C-H> 
    autocmd FileType help.supercollider nnoremap <C-J> <C-W><C-J>
    autocmd FileType help.supercollider nnoremap <C-K> <C-W><C-K>
    autocmd FileType help.supercollider nnoremap <C-L> <C-W><C-L>
    autocmd FileType help.supercollider nnoremap <C-H> <C-W><C-H>
```

**Expected behavior**

It would be cool if scnvim could respect the customization without me having to explicitly tell it to.

**Information**
- `nvim --version`: 0.3.8
- Operating system: Arch Linux
- Running scnvim in a Terminal/GUI: Termite terminal emulator, wayland/swaywm

**Comment by davidgranstrom** [comment]
@kflak I tried your mappings but I could not reproduce what you describe. Are there any other steps apart from opening a help file and navigate to another window from it?

Also, check the output of `:verbose nnoremap <C-J>` to see if something is overriding your mappings.

**Comment by kflak** [comment]
Thanks for the `:verbose` tip! It pointed me directly to the culprit, vim-latex.
