### ISSUE TITLE
"chansend" error on Ubuntu 18.04

### ISSUE THREAD

**Issue by madskjeldgaard** [davidgranstrom/scnvim#47]
just an FYI for others:
I just tested installing SCNvim on Ubuntu Studio 18.04 LTS which comes packaged with a quite old version of Nvim (0.2 something). 

When installing and running SCNvim on there, you will get a weird "chansend" error. This is fixed by installing a newer version of NVIM (0.3.1 like mentioned in the readme) by building neovim from source: https://github.com/neovim/neovim/wiki/Building-Neovim#build-prerequisites 
and then installing it by running `sudo make install`

**Comment by madskjeldgaard** [comment]
Sorry, this has a bug label but it is not a bug.

**Comment by davidgranstrom** [comment]
@madskjeldgaard Thanks! I'll pin this issue as it seems that it is a common question from users. 

Another great alternative to building nvim from source is to download and use the AppImage following [these instructions](https://github.com/neovim/neovim/wiki/Installing-Neovim#linux). I usually alias the AppImage to `/usr/local/bin/nvim` or some other directory in the user `$PATH`, e.g. `ln -s /path/to/nvim.appimage /usr/local/bin/nvim`

**Comment by davidgranstrom** [comment]
@madskjeldgaard I'm closing this issue now since the minimum supported version has increased to 0.4.3. There is also a check for nvim version in scnvim healthcheck routine (`:checkhealth`)

**Comment by madskjeldgaard** [comment]
> @madskjeldgaard I'm closing this issue now since the minimum supported version has increased to 0.4.3. There is also a check for nvim version in scnvim healthcheck routine (`:checkhealth`)

perfect!
