### ISSUE TITLE
ERROR: Primitive '_FileWrite' failed

### ISSUE THREAD

**Issue by kasimirmoi** [davidgranstrom/scnvim#53]
Hello! I followed the installation instructions accordingly, but I get this error when I start SuperCollider with :SCNvimStart

>compiling class library...
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-neuro'
	Found 847 primitives.
	Compiling directory '/usr/share/SuperCollider/SCClassLibrary'
	Compiling directory '/usr/share/SuperCollider/Extensions'
	Compiling directory '/home/neuro/.local/share/SuperCollider/Extensions'
	numentries = 821659 / 12054768 = 0.068
	5372 method selectors, 2244 classes
	method table size 13194984 bytes, big table size 96438144
	Number of Symbols 12209
	Byte Code Size 377004
	compiled 322 files in 0.71 seconds
Info: 4 methods are currently overwritten by extensions. To see which, execute:
MethodOverride.printAll
compile done
localhost : setting clientID to 0.
internal : setting clientID to 0.
Class tree inited in 0.01 seconds
ERROR: 
SCVim could not be initialized.
Consult the README to see how to install scvim.
ERROR: Primitive '_FileWrite' failed.
Failed.
RECEIVER:
Instance of File {    (0x564d9b689308, gc=A8, fmt=00, flg=00, set=02)
  instance variables [1]
    fileptr : nil
}
CALL STACK:
	MethodError:reportError
		arg this = <instance of PrimitiveFailedError>
	Nil:handleError
		arg this = nil
		arg error = <instance of PrimitiveFailedError>
	Thread:handleError
		arg this = <instance of Thread>
		arg error = <instance of PrimitiveFailedError>
	Object:throw
		arg this = <instance of PrimitiveFailedError>
	Object:primitiveFailed
		arg this = <instance of File>
	< closed FunctionDef >
		var classList = [*2243]
		var file = <instance of File>
		var hugeString = "syn keyword scObject FlowVar..."
		var basePath = nil
	Function:doOnStartUp
		arg this = <instance of Function>
	ArrayedCollection:do
		arg this = [*6]
		arg function = <instance of Function>
		var i = 4
	List:do
		arg this = <instance of List>
		arg function = <instance of Function>
	Meta_StartUp:run
		arg this = <instance of Meta_StartUp>
	Main:startup
		arg this = <instance of Main>
		var didWarnOverwrite = false
^^ The preceding error dump is for ERROR: Primitive '_FileWrite' failed.
Failed.
RECEIVER: a File

My first thought was that it could be caused by the user not having privileges to write somewhere, but I'm not sure?

nvim version: v0.4.3
OS: Void Linux, Kernel 5.4.13_2
terminal: st 0.8.2
I have pynvim installed.

**Comment by davidgranstrom** [comment]
@kasimirmoi Hi! It appears that this error is in fact caused by `scvim`.

```
ERROR:
SCVim could not be initialized.
Consult the README to see how to install scvim.
ERROR: Primitive '_FileWrite' failed.
```

Did it first appear when you installed `scnvim` or does the same error appear when you launch `scvim`?

**Comment by kasimirmoi** [comment]
@davidgranstrom I haven't installed or tried `scvim` at any point, `:SClangStart` gives me "Not an editor command". Do I need to install `scvim` separately before installing `scnvim`? I'm a bit confused.
What I've done: I had neovim installed, I had SuperCollider from void repository (SuperCollider 3.10.3). Then I installed `scnvim` according to the installation instructions using `vim-plug` and this error happens when I run `:SCNvimStart`. SuperCollider itself works fine when I use scide.

**Comment by davidgranstrom** [comment]
@kasimirmoi Okay, could you search for `SCVim.sc` in each of these directories?

```
'/usr/share/SuperCollider/SCClassLibrary'
'/usr/share/SuperCollider/Extensions'
'/home/neuro/.local/share/SuperCollider/Extensions'
```

Looking through the stack trace that you posted, I'm pretty sure it is related to this function https://github.com/supercollider/scvim/blob/master/sc/SCVim.sc#L44, here is the error message defined https://github.com/supercollider/scvim/blob/master/sc/SCVim.sc#L70

Could it be that the void package automatically installs `scvim`?

**Comment by davidgranstrom** [comment]
And to clarify, you don't need `scvim` to use `scnvim`, it is a standalone plugin with only internal dependencies.

**Comment by kasimirmoi** [comment]
@davidgranstrom Yes, I found `SCVim.sc` in `/usr/share/SuperCollider/Extensions/scide_scvim`
So, I'm a bit confused. Is `SCVim.sc` supposed to _not_ exist at all in this situation? I guess it's possible that the SuperCollider package in void repository had `scvim` included, but I need to look into it further.

**Comment by davidgranstrom** [comment]
@kasimirmoi ok, that file is not part of `scnvim` so you can safely move it/delete it (looks like scvim came pre-installed with your distros package manager). If you're still having trouble with the installation after that we can re-open this issue.

**Comment by kasimirmoi** [comment]
Thank you @davidgranstrom for helping me out, I got scnvim working now and I'm ready to start my SuperCollider journey! :)

**Comment by davidgranstrom** [comment]
@kasimirmoi no problems, great to hear! :)
