### ISSUE TITLE
Autocompletion / Snippets not working

### ISSUE THREAD

**Issue by salkin-mada** [davidgranstrom/scnvim#56]
**Describe the bug**
Autocompletion and snippets (pop up suggestions) not working.
:checkhealth -> all is good. But :UpdateRemotePlugins fails throwing an python error. python3 host registeret plugins ['scnvim'] deoplete no where to be found. rplugin.vim not generated.Therefore Deoplete fails to do it's magick. Deoplete is not loaded by default and even doing so manually via 'PlugStatus' does not change the situation.

**Fix**
Deoplete now requires 'msgpack' >= 1.0.0

```shell
pip uninstall msgpack-python
pip3 uninstall msgpack-python
pip3 install -U msgpack
```

or the following might be enough depending on your python setup.

`python3 -m pip install -U msgpack`

**Information**
- `nvim --version`: v0.3.4 
- Operating system: Debian 10
- Running scnvim in a Terminal/GUI: Kitty v0.15.1

**Comment by davidgranstrom** [comment]
Closing this since it's only related to Deoplete.
