### ISSUE TITLE
Error log regarding lua attempt to index nil value

### ISSUE THREAD

**Issue by gilfuser** [davidgranstrom/scnvim#65]
Hi.
When I evaluate `SCNvimStart` I'm receiving an error log. I couldn't notice any bug because of it, though.

Here it is:
![Screenshot_2020-04-05_00-25-22](https://user-images.githubusercontent.com/9404458/78466458-c5650680-76d7-11ea-93c0-d7bc4bbee6b5.png)

best regards,
Gil

**Comment by davidgranstrom** [comment]
@gilfuser Thanks for the report. Which version on `nvim` do you use? You can run `:checkhealth` to diagnose if you're version is too low for scnvim.

**Comment by gilfuser** [comment]
Hi.
Thank you.
That was it!
Ubuntu was misleading me telling me I had the newest version.
Closing this.

Cheers,
Gil
