### ISSUE TITLE
scnvim should not interfere with user's tab settings

### ISSUE THREAD

**Issue by dathinaios** [davidgranstrom/scnvim#66]
In  `scnvim/ftplugin/supercollider/supercollider.vim`  the following settings are defined:
```
" indentation
setlocal tabstop=4
setlocal softtabstop=4
setlocal shiftwidth=4
```
I suggest we remove this as it is quite intrusive to override user settings in this manner.

**Comment by davidgranstrom** [comment]
@dathinaios Yes, I agree!
