### ISSUE TITLE
[FR] Syntax checking with YCM

### ISSUE THREAD

**Issue by madskjeldgaard** [davidgranstrom/scnvim#69]
This is not a bug but a feature request.

Me and @kflak have both started to use YouCompleteMe lately for cpp/OpenFrameworks stuff, and we started dreaming about this idea: To use the YCM syntax checker/debugger system for SuperCollider-development as well integrated with SCNVim. 

I'm not sure how it would be technically possible but it would be really amazing to have YCM hook into the SCNVim syntax-files and get an amazing IDE-like experience. 

YCM seems to need a `omnifunc` to hook into to do this and I don't know the insides of SCNVim well enough right now to know whether this is the case here but I thought I would post this here and you can file it under "dreams for SCNVim" :)

https://github.com/ycm-core/YouCompleteMe#writing-new-semantic-completers

**Comment by salkin-mada** [comment]
include me in the dreamers

**Comment by madskjeldgaard** [comment]
The real solution to this issue is outside of SCNVIM. I think what is needed is an LSP implementation for SC but until that's seen the light of day, I don't think this SCNVIM should have this as an issue. There's talk of that here: https://github.com/crucialfelix/supercolliderjs/issues/36
