### ISSUE TITLE
Native plugin documentation

### ISSUE THREAD

**Issue by davidgranstrom** [davidgranstrom/scnvim#8]
Write help docs:

- [x] Vim help
- [x] schelp

**Comment by kflak** [comment]
I am so, so, so very interested in this feature. I am currently on wayland/sway, and the schelp stuff is completely broken. The only way is working is by starting scide with the --disable-gpu flag... If there is anything I can do to help with this (mainly in terms of testing, as this seems way out of my depth when it comes to vimscript and js...), then let me know!

**Comment by madskjeldgaard** [comment]
I agree with @kflak (ps. have you tried the latest version of SC? For me it fixed some of the many bugs with the help system, enough to make it usable but far from good) 

The biggest dream situation would not only be a native help system that works but with the extra bonus that it is interactive like the one in the IDE, but I'm guessing this will be inherent if it's vim native.

**Comment by madskjeldgaard** [comment]
* On MacOS that is

**Comment by kflak** [comment]
Yeah, on Linux/wayland the help situation is even more dire... When I say broken I mean literally broken, with the help browser crashing, graphics corrupting and bringing the whole sclang down with it. Check [issue #53](https://github.com/supercollider/scvim/issues/53) over at scvim for more details if you feel like a bit of weekend reading ;-)

**Comment by kflak** [comment]
I ended up remapping K to just simply launching a browser directly on the scdocs search page...

**Comment by davidgranstrom** [comment]
The title of this issue was perhaps a bit misleading, its about writing native documentation for the scnvim plugin in both nvim and SC. :)

However, an integrated help system is one of the features I would like to add in the near future. The work is being made in #6, I'll let you know when its ready to try out!
