### ISSUE TITLE
[BUG] Soundfile corruption on close while recording

### ISSUE THREAD

**Issue by kflak** [davidgranstrom/scnvim#80]
`s.record("~/test.wav")` -> quit scnvim without stopping the recording -> corrupt sound file.
**Expected behavior**
Doing the same in scide does not corrupt the sound file.
**Steps to reproduce**
See above.
**Information**
- `nvim --version`: NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.3/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

- Operating system: Arch Linux 5.6.10-rt5-2-rt
- Running scnvim in a Terminal/GUI: terminal (termite on swaywm/wayland)

**Comment by davidgranstrom** [comment]
@kflak Thanks for the report! I have started a PR which solves this, but I still need to do some investigation before I can merge. (there seem to be a problem with the lua handlers after a recompile, will look into that shortly)

**Comment by davidgranstrom** [comment]
@kflak I think I have something working now. Please feel free to try out #82 if you have the time!

**Comment by kflak** [comment]
Sweet! I'll give it a spin when I have a moment. Arts Council application deadline coming up tomorrow, so....
