### ISSUE TITLE
[BUG] Help files and args not showing. 

### ISSUE THREAD

**Issue by jordanwhitede** [davidgranstrom/scnvim#84]
Args are not showing when I open brackets after UGens. Also, when I hit K, I get a black 'loading' window.

On the GitHub page for SCNvim it seems like these are features. If I'm missing something that is required in the configuration then I'm sorry!

**Information**
- `nvim --version`: 0.5.0-dev
- Operating system: Ubuntu 18.04.04 LTS
- Running scnvim in a Terminal/GUI: Terminal

**Comment by davidgranstrom** [comment]
@jordanwhitede What version of SuperCollider are you running? Also, make sure that the SCNvim SuperCollider classes are correctly installed (e.g. you can try to evaluate `SCNvim.currentPath` in a SuperCollider session and it should print the current buffer path in the post window).

**Comment by jordanwhitede** [comment]
Thanks for your patience!

I'm running 3.11.0, compiled from source. SCNvim.currentPath returns the path of the file I'm editing.

**Comment by davidgranstrom** [comment]
@jordanwhitede Thanks for the info! I just tested the HelpBrowser with 3.11.0 (b95b6da52) and it seems to be working fine. I'm not sure what could cause this.. does the help system work as expected in ScIDE?

Also not sure why you aren't seeing the argument hints, I think I will need to have a look at your init.vim in order to investigate further. Could you post a link to it, or post the content here in the tracker?

**Comment by jordanwhitede** [comment]
Help system works fine in ScIDE. 

Here's my init.vim:

´´´  1 "colour scheme
  2 color zenburn
  3 syntax on
  4 
  5 syntax enable " enable syntax processing
  6 
  7 set tabstop=4 " number of visual spaces per TAB
  8 
  9 set softtabstop=4 " number of spaces in tab when editing
 10 
 11 set expandtab " tabs are spaces
 12 
 13 set number " show line numbers
 14 
 15 set showcmd "show command in bottom bar
 16 
 17 set cursorline " highlight current line
 18 
 19 filetype indent on " load filetype-specific indent files
 20 
 21 set wildmenu " visual autocomplete for command menu
 22 
 23 set lazyredraw " redraw only when necessary
 24 
 25 set showmatch "highlight matching brackets
 26 
 27 set incsearch " search as characters are entered
 28 
 29 set hlsearch " highlight matches
 30 
 31 nnoremap <leader><space> :nohlsearch<CR>
 32 
 33 "move vertically by visual line
 34 nnoremap j gj
 35 nnoremap k gk
 36 
 37 " highlight last inserted text
 38 nnoremap gV `[v]`
 39 
 40 " backupdir set to tmp for some reason
 41                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
 42 set backup
 43 set backupdir=~/.vim-tmp,~/.tmp,/tmp,/var/tmp,/tmp
 44 set backupskip=/tmp/*,/private/tmp/*
 45 set directory=~/.vim-tmp,~/.tmp,~/tmp,/war/tmp,/tmp
 46 set writebackup
 47 
 48 
 49 "vim-plug
 50 call plug#begin('/usr/bin/nvim/site/pack/git-plugins/start')
 51 Plug 'davidgranstrom/scnvim'
 52 Plug 'SirVer/ultisnips'
 53 call plug#end()
 54 
 55 " scnvim
 56 "
 57 " post window at the bottom
 58 let g:scnvim_postwin_orientation = 'h'
 59 
 60 " hopefully helps w arguments
 61 let g:scnvim_echo_args = 1
 62 
 63 " remap send block
 64 nmap <F5> <Plug>(scnvim-send-block)
 65 
 66 " remap post window toggle
 67 nmap <Space> <Plug>(scnvim-postwindow-toggle)
 68 
 69 " eval flash colors
 70 highlight SCNvimEval guifg=black guibg = cyan ctermfg=black ctermbg=cyan
 71 " this autocmd keeps the custom highlight when changing color schemes
 72 augroup scnvim_vimrc
 73         autocmd!
 74         autocmd ColorScheme * \ highlight SCNvimEval guifg=black guibg=cyan ctermfg=black ctermbg=cyan
 75 
 76 "hard coded path to sclang executable
 77 let g:scnvim_sclang_executable = '/usr/local/bin/sclang'
 78 
 79 
 80 " enable snippets support
 81 let g:UltiSnipsSnippetDirectories = ['UltiSnips', 'scnvim-data']
 82 
 83 " create a custom status line for sc buffers
 84 function! s:set_sclang_statusline()
 85         setlocal stl=
 86         setlocal stl+=%f
 87         setlocal stl+=%=
 88         setlocal stl+=%(%l,%c%)                                                                                                                                                                                                                                                                                                                                                                                                                                                         
 89         setlocal stl+=\ \|                                                                                                                                                                                                                                                                                                                                                                                                                                                              
 90         setlocal stl+=%24.24{scnvim#statusline#server_status()}                                                                                                                                                                                                                                                                                                                                                                                                                         
 91 endfunction                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
 92                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
 93 augroup scnvim_st1                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
 94         autocmd!                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
 95         autocmd FileType supercollider call <SID>set_sclang_statusline()                                                                                                                                                                                                                                                                                                                                                                                                                
 96 augroup END                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
~
~
~
~
~
~
~
~
~
~
~
init.vim                                                                                                                                                                                                                                                                                                                                                                                                                                                                  41,0-1         All

´´´

**Comment by davidgranstrom** [comment]
@jordanwhitede Thanks! Have you called `:SCNvimTags` in nvim after you've started a SuperCollider session? I just realized that it is needed for the arghints to work properly (it will also enable syntax highlighting etc.)

**Comment by jordanwhitede** [comment]
OK, I ran that and it showed the args. I also checked the scnvim help file and realised I hadn't installed pandoc. So this one's my fault, whoops! I'll read the help files more carefully before logging bugs in the future!

**Comment by davidgranstrom** [comment]
Okay, happy to hear that it's working!
